SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

--CREATE TABLES 
CREATE TABLE ZIPCITY
(
	id      INT         IDENTITY(1,1),
	zipCode INT,
	city    VARCHAR(25),

	PRIMARY KEY (id)
);

CREATE TABLE CATEGORY
(
	id   INT          IDENTITY(1,1),
	type VARCHAR(100),

	PRIMARY KEY (id)
);

CREATE TABLE SUPPLIER
(
	id      INT          IDENTITY(1,1),
	name    VARCHAR(100),
	country VARCHAR(100),
	cvrNo   VARCHAR(8),
	phone   VARCHAR(12),
	email   VARCHAR(100),

	PRIMARY KEY (id)
);

CREATE TABLE CUSTOMER
(
	id        INT          IDENTITY(1,1),
	fName     VARCHAR(30),
	lName     VARCHAR(30),
	email     VARCHAR(100),
	address   VARCHAR(100),
	phone     VARCHAR(12),
	zipcityId INT

		PRIMARY KEY (id),
	FOREIGN KEY (zipcityId) REFERENCES ZIPCITY (id)
);

CREATE TABLE MYORDER
(
	id         INT IDENTITY(1,1),
	delivery   BIT,
	processed  BIT,
	customerId INT,

	PRIMARY KEY (id),
	FOREIGN KEY (customerId) REFERENCES CUSTOMER (id)
);

CREATE TABLE PRODUCT
(
	id          INT           IDENTITY(1,1),
	name        VARCHAR(2048),
	price       DEC,
	description VARCHAR(2048),
	supplierId  INT,
	categoryId  INT,

	PRIMARY KEY (id),
	FOREIGN KEY (supplierId) REFERENCES SUPPLIER (id),
	FOREIGN KEY (categoryId) REFERENCES CATEGORY (id)
);

CREATE TABLE UNIQUEPRODUCT
(
	id        INT          IDENTITY(1,1),
	serialNo  VARCHAR(100) UNIQUE,
	warranty  VARCHAR(30),
	productId INT,

	PRIMARY KEY (id),
	FOREIGN KEY (productId) REFERENCES PRODUCT (id)
);


CREATE TABLE ORDERLINE
(
	id      INT IDENTITY(1,1),
	orderId INT,

	PRIMARY KEY (id),
	FOREIGN KEY(orderId) REFERENCES MYORDER(id)
);


CREATE TABLE ORDERLINELIST
(
	id              INT IDENTITY(1,1),
	orderLineId     INT,
	UniqueProductId INT,

	PRIMARY KEY (id),
	FOREIGN KEY (orderLineId) REFERENCES ORDERLINE (id),
	FOREIGN KEY (UniqueProductId) REFERENCES UNIQUEPRODUCT (id)
);

CREATE TABLE EMPLOYEE
(
	id       INT          IDENTITY(1,1),
	fName    VARCHAR(30),
	lName    VARCHAR(30),
	username VARCHAR(20),
	password VARCHAR(100),
	salt     VARCHAR(100)

		PRIMARY KEY (id)
);

--INSERT INTO EMPLOYEE
INSERT INTO EMPLOYEE
VALUES
	('Christian Ib', 'Sørensen', 'Chrib', 'J1mRjPUZReAJ7bAXrQDQ799lViY=', 'JGFQ5WswIkQ7jkzm5d5wx/x5IofXbdLY7k7rkLVYsKw=');
INSERT INTO EMPLOYEE
VALUES
	('Aksel', 'Gregersen', 'Greek', 'tUHpguXBugMyLgUXQUDrYhis6Fo=', 'Gs+ma8eQkQLWoz3M6PPm8oSz0h2AHVBC0qCQEcoaL3I=');
INSERT INTO EMPLOYEE
VALUES
	('Sævar', 'Chanukah', 'Serveren', 'g6FU+N7qKdHN+NuIxLygSyivVaU=', 'lUVhLGLq8SHjlkfCF8pu6OJf9lKjQ6EoOWJ/XlJXJZw=');
INSERT INTO EMPLOYEE
VALUES
	('Daniel', 'Sletskov', 'Daniel', 'byy2Gz8CDAQQcTS+ZFlAFquMeuk=', 'YJvsJklk047SAXFbqbIF74pv3m7Dkn9E5TO8FJkZcy4=');
INSERT INTO EMPLOYEE
VALUES
	('Mathias', 'Nielsen', '1Brugernavn', 'HRTCpSuprJPt00qu/gR72nAJm/M=', 'lfMly3HLfaSM2KO1NI99SAYfTSqJvJXJj1dgVOn8O4k=');

--INSERT INTO ZIPCITY
INSERT INTO ZIPCITY
VALUES
	(1050, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1051, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1052, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1053, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1054, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1055, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1055, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1056, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1057, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1058, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1059, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1060, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1061, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1062, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1063, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1064, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1065, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1066, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1067, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1068, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1069, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1070, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1071, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1072, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1073, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1074, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1100, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1101, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1102, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1103, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1104, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1105, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1106, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1107, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1110, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1111, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1112, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1113, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1114, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1115, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1116, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1117, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1118, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1119, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1120, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1121, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1122, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1123, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1124, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1125, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1126, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1127, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1128, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1129, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1130, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1131, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1150, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1151, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1152, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1153, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1154, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1155, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1156, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1157, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1158, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1159, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1160, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1161, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1162, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1163, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1164, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1165, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1165, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1166, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1167, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1168, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1169, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1170, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1171, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1172, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1173, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1174, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1175, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1200, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1201, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1202, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1203, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1204, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1205, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1206, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1207, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1208, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1209, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1210, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1211, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1212, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1213, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1214, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1215, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1216, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1218, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1218, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1218, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1218, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1218, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1218, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1219, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1220, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1221, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1250, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1251, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1252, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1253, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1254, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1255, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1256, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1257, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1259, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1259, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1260, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1261, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1263, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1263, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1264, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1265, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1266, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1267, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1268, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1270, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1271, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1300, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1301, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1302, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1303, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1304, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1306, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1307, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1307, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1308, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1309, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1310, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1311, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1312, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1313, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1314, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1315, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1316, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1317, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1318, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1319, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1320, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1321, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1322, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1323, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1324, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1325, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1326, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1327, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1328, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1329, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1350, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1352, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1353, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1354, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1355, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1356, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1357, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1358, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1359, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1359, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1360, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1361, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1361, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1362, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1363, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1364, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1365, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1366, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1367, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1368, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1369, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1370, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1371, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1400, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1400, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1401, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1402, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1402, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1402, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1402, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1402, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1403, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1404, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1406, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1407, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1408, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1409, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1410, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1411, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1411, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1412, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1413, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1414, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1415, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1416, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1417, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1418, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1419, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1420, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1421, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1422, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1423, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1424, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1425, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1426, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1427, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1428, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1429, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1430, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1431, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1432, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1432, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1432, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1433, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1433, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1433, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1433, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1433, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1433, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1433, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1434, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1434, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1435, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1436, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1436, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1436, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1436, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1436, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1436, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1437, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1438, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1438, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1438, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1438, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1438, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1439, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1440, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1441, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1441, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1441, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1450, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1451, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1452, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1453, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1454, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1455, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1456, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1457, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1458, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1459, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1460, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1461, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1462, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1463, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1464, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1465, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1466, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1467, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1468, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1470, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1471, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1472, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1473, 'København K');
INSERT INTO ZIPCITY
VALUES
	(1550, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1550, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1551, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1552, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1553, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1553, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1554, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1555, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1556, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1557, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1558, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1559, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1560, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1561, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1561, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1562, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1563, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1564, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1567, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1568, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1569, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1570, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1570, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1571, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1572, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1573, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1574, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1575, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1576, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1577, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1577, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1577, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1600, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1601, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1602, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1603, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1604, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1605, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1606, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1607, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1608, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1609, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1610, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1611, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1612, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1613, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1614, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1615, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1616, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1617, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1618, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1619, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1620, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1620, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1621, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1622, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1623, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1624, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1631, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1632, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1633, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1634, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1635, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1650, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1651, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1652, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1653, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1654, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1655, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1656, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1657, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1658, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1659, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1660, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1660, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1661, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1662, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1663, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1664, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1665, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1666, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1667, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1668, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1669, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1670, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1671, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1671, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1672, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1673, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1674, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1675, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1676, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1677, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1699, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1700, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1701, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1702, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1703, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1704, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1705, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1706, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1707, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1708, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1709, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1710, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1711, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1711, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1712, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1713, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1714, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1715, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1716, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1717, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1718, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1719, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1720, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1721, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1722, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1723, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1724, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1725, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1726, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1727, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1728, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1729, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1730, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1731, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1732, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1733, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1734, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1735, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1736, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1737, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1738, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1739, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1749, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1750, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1751, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1752, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1753, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1754, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1755, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1756, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1757, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1758, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1759, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1760, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1761, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1762, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1763, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1764, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1765, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1766, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1770, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1771, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1772, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1773, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1774, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1775, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1777, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1799, 'København V');
INSERT INTO ZIPCITY
VALUES
	(1800, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1801, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1802, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1803, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1804, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1805, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1806, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1807, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1808, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1809, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1810, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1811, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1812, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1813, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1814, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1815, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1816, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1817, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1818, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1819, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1820, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1822, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1823, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1824, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1825, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1826, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1827, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1828, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1829, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1850, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1851, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1852, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1853, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1854, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1855, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1856, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1857, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1860, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1861, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1862, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1863, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1864, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1865, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1866, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1867, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1868, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1870, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1871, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1872, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1873, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1874, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1875, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1876, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1877, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1878, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1879, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1900, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1901, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1902, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1903, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1904, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1905, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1906, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1908, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1909, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1910, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1911, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1912, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1913, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1914, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1915, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1916, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1917, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1920, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1921, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1922, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1923, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1924, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1925, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1926, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1927, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1928, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1950, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1951, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1952, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1953, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1954, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1955, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1956, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1957, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1958, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1959, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1960, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1961, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1962, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1963, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1964, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1965, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1966, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1967, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1970, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1971, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1972, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1973, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(1974, 'Frederiksberg C');
INSERT INTO ZIPCITY
VALUES
	(2000, 'Frederiksberg');
INSERT INTO ZIPCITY
VALUES
	(2100, 'København Ø');
INSERT INTO ZIPCITY
VALUES
	(2150, 'Nordhavn');
INSERT INTO ZIPCITY
VALUES
	(2200, 'København N');
INSERT INTO ZIPCITY
VALUES
	(2300, 'København S');
INSERT INTO ZIPCITY
VALUES
	(2400, 'København NV');
INSERT INTO ZIPCITY
VALUES
	(2412, 'Julemandens by');
INSERT INTO ZIPCITY
VALUES
	(2450, 'København SV');
INSERT INTO ZIPCITY
VALUES
	(2500, 'Valby');
INSERT INTO ZIPCITY
VALUES
	(2600, 'Glostrup');
INSERT INTO ZIPCITY
VALUES
	(2605, 'Brøndby');
INSERT INTO ZIPCITY
VALUES
	(2610, 'Rødovre');
INSERT INTO ZIPCITY
VALUES
	(2620, 'Albertslund');
INSERT INTO ZIPCITY
VALUES
	(2625, 'Vallensbæk');
INSERT INTO ZIPCITY
VALUES
	(2630, 'Taastrup');
INSERT INTO ZIPCITY
VALUES
	(2635, 'Ishøj');
INSERT INTO ZIPCITY
VALUES
	(2640, 'Hedehusene');
INSERT INTO ZIPCITY
VALUES
	(2650, 'Hvidovre');
INSERT INTO ZIPCITY
VALUES
	(2660, 'Brøndby Strand');
INSERT INTO ZIPCITY
VALUES
	(2665, 'Vallensbæk Strand');
INSERT INTO ZIPCITY
VALUES
	(2670, 'Greve');
INSERT INTO ZIPCITY
VALUES
	(2680, 'Solrød Strand');
INSERT INTO ZIPCITY
VALUES
	(2690, 'Karlslunde');
INSERT INTO ZIPCITY
VALUES
	(2700, 'Brønshøj');
INSERT INTO ZIPCITY
VALUES
	(2720, 'Vanløse');
INSERT INTO ZIPCITY
VALUES
	(2730, 'Herlev');
INSERT INTO ZIPCITY
VALUES
	(2740, 'Skovlunde');
INSERT INTO ZIPCITY
VALUES
	(2750, 'Ballerup');
INSERT INTO ZIPCITY
VALUES
	(2760, 'Måløv');
INSERT INTO ZIPCITY
VALUES
	(2765, 'Smørum');
INSERT INTO ZIPCITY
VALUES
	(2770, 'Kastrup');
INSERT INTO ZIPCITY
VALUES
	(2791, 'Dragør');
INSERT INTO ZIPCITY
VALUES
	(2800, 'Kongens Lyngby');
INSERT INTO ZIPCITY
VALUES
	(2820, 'Gentofte');
INSERT INTO ZIPCITY
VALUES
	(2830, 'Virum');
INSERT INTO ZIPCITY
VALUES
	(2840, 'Holte');
INSERT INTO ZIPCITY
VALUES
	(2850, 'Nærum');
INSERT INTO ZIPCITY
VALUES
	(2860, 'Søborg');
INSERT INTO ZIPCITY
VALUES
	(2870, 'Dyssegård');
INSERT INTO ZIPCITY
VALUES
	(2880, 'Bagsværd');
INSERT INTO ZIPCITY
VALUES
	(2900, 'Hellerup');
INSERT INTO ZIPCITY
VALUES
	(2920, 'Charlottenlund');
INSERT INTO ZIPCITY
VALUES
	(2930, 'Klampenborg');
INSERT INTO ZIPCITY
VALUES
	(2942, 'Skodsborg');
INSERT INTO ZIPCITY
VALUES
	(2950, 'Vedbæk');
INSERT INTO ZIPCITY
VALUES
	(2960, 'Rungsted Kyst');
INSERT INTO ZIPCITY
VALUES
	(2970, 'Hørsholm');
INSERT INTO ZIPCITY
VALUES
	(2980, 'Kokkedal');
INSERT INTO ZIPCITY
VALUES
	(2990, 'Nivå');
INSERT INTO ZIPCITY
VALUES
	(3000, 'Helsingør');
INSERT INTO ZIPCITY
VALUES
	(3050, 'Humlebæk');
INSERT INTO ZIPCITY
VALUES
	(3060, 'Espergærde');
INSERT INTO ZIPCITY
VALUES
	(3070, 'Snekkersten');
INSERT INTO ZIPCITY
VALUES
	(3080, 'Tikøb');
INSERT INTO ZIPCITY
VALUES
	(3100, 'Hornbæk');
INSERT INTO ZIPCITY
VALUES
	(3120, 'Dronningmølle');
INSERT INTO ZIPCITY
VALUES
	(3140, 'Ålsgårde');
INSERT INTO ZIPCITY
VALUES
	(3150, 'Hellebæk');
INSERT INTO ZIPCITY
VALUES
	(3200, 'Helsinge');
INSERT INTO ZIPCITY
VALUES
	(3210, 'Vejby');
INSERT INTO ZIPCITY
VALUES
	(3220, 'Tisvildeleje');
INSERT INTO ZIPCITY
VALUES
	(3230, 'Græsted');
INSERT INTO ZIPCITY
VALUES
	(3250, 'Gilleleje');
INSERT INTO ZIPCITY
VALUES
	(3300, 'Frederiksværk');
INSERT INTO ZIPCITY
VALUES
	(3310, 'Ølsted');
INSERT INTO ZIPCITY
VALUES
	(3320, 'Skævinge');
INSERT INTO ZIPCITY
VALUES
	(3330, 'Gørløse');
INSERT INTO ZIPCITY
VALUES
	(3360, 'Liseleje');
INSERT INTO ZIPCITY
VALUES
	(3370, 'Melby');
INSERT INTO ZIPCITY
VALUES
	(3390, 'Hundested');
INSERT INTO ZIPCITY
VALUES
	(3400, 'Hillerød');
INSERT INTO ZIPCITY
VALUES
	(3450, 'Allerød');
INSERT INTO ZIPCITY
VALUES
	(3460, 'Birkerød');
INSERT INTO ZIPCITY
VALUES
	(3480, 'Fredensborg');
INSERT INTO ZIPCITY
VALUES
	(3490, 'Kvistgård');
INSERT INTO ZIPCITY
VALUES
	(3500, 'Værløse');
INSERT INTO ZIPCITY
VALUES
	(3520, 'Farum');
INSERT INTO ZIPCITY
VALUES
	(3540, 'Lynge');
INSERT INTO ZIPCITY
VALUES
	(3550, 'Slangerup');
INSERT INTO ZIPCITY
VALUES
	(3600, 'Frederikssund');
INSERT INTO ZIPCITY
VALUES
	(3630, 'Jægerspris');
INSERT INTO ZIPCITY
VALUES
	(3650, 'Ølstykke');
INSERT INTO ZIPCITY
VALUES
	(3660, 'Stenløse');
INSERT INTO ZIPCITY
VALUES
	(3670, 'Veksø Sjælland');
INSERT INTO ZIPCITY
VALUES
	(3700, 'Rønne');
INSERT INTO ZIPCITY
VALUES
	(3720, 'Aakirkeby');
INSERT INTO ZIPCITY
VALUES
	(3730, 'Nexø');
INSERT INTO ZIPCITY
VALUES
	(3740, 'Svaneke');
INSERT INTO ZIPCITY
VALUES
	(3751, 'Østermarie');
INSERT INTO ZIPCITY
VALUES
	(3760, 'Gudhjem');
INSERT INTO ZIPCITY
VALUES
	(3770, 'Allinge');
INSERT INTO ZIPCITY
VALUES
	(3782, 'Klemensker');
INSERT INTO ZIPCITY
VALUES
	(3790, 'Hasle');
INSERT INTO ZIPCITY
VALUES
	(4000, 'Roskilde');
INSERT INTO ZIPCITY
VALUES
	(4030, 'Tune');
INSERT INTO ZIPCITY
VALUES
	(4040, 'Jyllinge');
INSERT INTO ZIPCITY
VALUES
	(4050, 'Skibby');
INSERT INTO ZIPCITY
VALUES
	(4060, 'Kirke Såby');
INSERT INTO ZIPCITY
VALUES
	(4070, 'Kirke Hyllinge');
INSERT INTO ZIPCITY
VALUES
	(4100, 'Ringsted');
INSERT INTO ZIPCITY
VALUES
	(4130, 'Viby Sjælland');
INSERT INTO ZIPCITY
VALUES
	(4140, 'Borup');
INSERT INTO ZIPCITY
VALUES
	(4160, 'Herlufmagle');
INSERT INTO ZIPCITY
VALUES
	(4171, 'Glumsø');
INSERT INTO ZIPCITY
VALUES
	(4173, 'Fjenneslev');
INSERT INTO ZIPCITY
VALUES
	(4174, 'Jystrup Midtsj');
INSERT INTO ZIPCITY
VALUES
	(4180, 'Sorø');
INSERT INTO ZIPCITY
VALUES
	(4190, 'Munke Bjergby');
INSERT INTO ZIPCITY
VALUES
	(4200, 'Slagelse');
INSERT INTO ZIPCITY
VALUES
	(4220, 'Korsør');
INSERT INTO ZIPCITY
VALUES
	(4230, 'Skælskør');
INSERT INTO ZIPCITY
VALUES
	(4241, 'Vemmelev');
INSERT INTO ZIPCITY
VALUES
	(4242, 'Boeslunde');
INSERT INTO ZIPCITY
VALUES
	(4243, 'Rude');
INSERT INTO ZIPCITY
VALUES
	(4244, 'Agersø');
INSERT INTO ZIPCITY
VALUES
	(4245, 'Omø');
INSERT INTO ZIPCITY
VALUES
	(4250, 'Fuglebjerg');
INSERT INTO ZIPCITY
VALUES
	(4261, 'Dalmose');
INSERT INTO ZIPCITY
VALUES
	(4262, 'Sandved');
INSERT INTO ZIPCITY
VALUES
	(4270, 'Høng');
INSERT INTO ZIPCITY
VALUES
	(4281, 'Gørlev');
INSERT INTO ZIPCITY
VALUES
	(4291, 'Ruds Vedby');
INSERT INTO ZIPCITY
VALUES
	(4293, 'Dianalund');
INSERT INTO ZIPCITY
VALUES
	(4295, 'Stenlille');
INSERT INTO ZIPCITY
VALUES
	(4296, 'Nyrup');
INSERT INTO ZIPCITY
VALUES
	(4300, 'Holbæk');
INSERT INTO ZIPCITY
VALUES
	(4305, 'Orø');
INSERT INTO ZIPCITY
VALUES
	(4320, 'Lejre');
INSERT INTO ZIPCITY
VALUES
	(4330, 'Hvalsø');
INSERT INTO ZIPCITY
VALUES
	(4340, 'Tølløse');
INSERT INTO ZIPCITY
VALUES
	(4350, 'Ugerløse');
INSERT INTO ZIPCITY
VALUES
	(4360, 'Kirke Eskilstrup');
INSERT INTO ZIPCITY
VALUES
	(4370, 'Store Merløse');
INSERT INTO ZIPCITY
VALUES
	(4390, 'Vipperød');
INSERT INTO ZIPCITY
VALUES
	(4400, 'Kalundborg');
INSERT INTO ZIPCITY
VALUES
	(4420, 'Regstrup');
INSERT INTO ZIPCITY
VALUES
	(4440, 'Mørkøv');
INSERT INTO ZIPCITY
VALUES
	(4450, 'Jyderup');
INSERT INTO ZIPCITY
VALUES
	(4460, 'Snertinge');
INSERT INTO ZIPCITY
VALUES
	(4470, 'Svebølle');
INSERT INTO ZIPCITY
VALUES
	(4480, 'Store Fuglede');
INSERT INTO ZIPCITY
VALUES
	(4490, 'Jerslev Sjælland');
INSERT INTO ZIPCITY
VALUES
	(4500, 'Nykøbing Sj');
INSERT INTO ZIPCITY
VALUES
	(4520, 'Svinninge');
INSERT INTO ZIPCITY
VALUES
	(4532, 'Gislinge');
INSERT INTO ZIPCITY
VALUES
	(4534, 'Hørve');
INSERT INTO ZIPCITY
VALUES
	(4540, 'Fårevejle');
INSERT INTO ZIPCITY
VALUES
	(4550, 'Asnæs');
INSERT INTO ZIPCITY
VALUES
	(4560, 'Vig');
INSERT INTO ZIPCITY
VALUES
	(4571, 'Grevinge');
INSERT INTO ZIPCITY
VALUES
	(4572, 'Nørre Asmindrup');
INSERT INTO ZIPCITY
VALUES
	(4573, 'Højby');
INSERT INTO ZIPCITY
VALUES
	(4581, 'Rørvig');
INSERT INTO ZIPCITY
VALUES
	(4583, 'Sjællands Odde');
INSERT INTO ZIPCITY
VALUES
	(4591, 'Føllenslev');
INSERT INTO ZIPCITY
VALUES
	(4592, 'Sejerø');
INSERT INTO ZIPCITY
VALUES
	(4593, 'Eskebjerg');
INSERT INTO ZIPCITY
VALUES
	(4600, 'Køge');
INSERT INTO ZIPCITY
VALUES
	(4621, 'Gadstrup');
INSERT INTO ZIPCITY
VALUES
	(4622, 'Havdrup');
INSERT INTO ZIPCITY
VALUES
	(4623, 'Lille Skensved');
INSERT INTO ZIPCITY
VALUES
	(4632, 'Bjæverskov');
INSERT INTO ZIPCITY
VALUES
	(4640, 'Faxe');
INSERT INTO ZIPCITY
VALUES
	(4652, 'Hårlev');
INSERT INTO ZIPCITY
VALUES
	(4653, 'Karise');
INSERT INTO ZIPCITY
VALUES
	(4654, 'Faxe Ladeplads');
INSERT INTO ZIPCITY
VALUES
	(4660, 'Store Heddinge');
INSERT INTO ZIPCITY
VALUES
	(4671, 'Strøby');
INSERT INTO ZIPCITY
VALUES
	(4672, 'Klippinge');
INSERT INTO ZIPCITY
VALUES
	(4673, 'Rødvig Stevns');
INSERT INTO ZIPCITY
VALUES
	(4681, 'Herfølge');
INSERT INTO ZIPCITY
VALUES
	(4682, 'Tureby');
INSERT INTO ZIPCITY
VALUES
	(4683, 'Rønnede');
INSERT INTO ZIPCITY
VALUES
	(4684, 'Holmegaard');
INSERT INTO ZIPCITY
VALUES
	(4690, 'Haslev');
INSERT INTO ZIPCITY
VALUES
	(4700, 'Næstved');
INSERT INTO ZIPCITY
VALUES
	(4720, 'Præstø');
INSERT INTO ZIPCITY
VALUES
	(4733, 'Tappernøje');
INSERT INTO ZIPCITY
VALUES
	(4735, 'Mern');
INSERT INTO ZIPCITY
VALUES
	(4736, 'Karrebæksminde');
INSERT INTO ZIPCITY
VALUES
	(4750, 'Lundby');
INSERT INTO ZIPCITY
VALUES
	(4760, 'Vordingborg');
INSERT INTO ZIPCITY
VALUES
	(4771, 'Kalvehave');
INSERT INTO ZIPCITY
VALUES
	(4772, 'Langebæk');
INSERT INTO ZIPCITY
VALUES
	(4773, 'Stensved');
INSERT INTO ZIPCITY
VALUES
	(4780, 'Stege');
INSERT INTO ZIPCITY
VALUES
	(4791, 'Borre');
INSERT INTO ZIPCITY
VALUES
	(4792, 'Askeby');
INSERT INTO ZIPCITY
VALUES
	(4793, 'Bogø By');
INSERT INTO ZIPCITY
VALUES
	(4800, 'Nykøbing F');
INSERT INTO ZIPCITY
VALUES
	(4840, 'Nørre Alslev');
INSERT INTO ZIPCITY
VALUES
	(4850, 'Stubbekøbing');
INSERT INTO ZIPCITY
VALUES
	(4862, 'Guldborg');
INSERT INTO ZIPCITY
VALUES
	(4863, 'Eskilstrup');
INSERT INTO ZIPCITY
VALUES
	(4871, 'Horbelev');
INSERT INTO ZIPCITY
VALUES
	(4872, 'Idestrup');
INSERT INTO ZIPCITY
VALUES
	(4873, 'Væggerløse');
INSERT INTO ZIPCITY
VALUES
	(4874, 'Gedser');
INSERT INTO ZIPCITY
VALUES
	(4880, 'Nysted');
INSERT INTO ZIPCITY
VALUES
	(4891, 'Toreby L');
INSERT INTO ZIPCITY
VALUES
	(4892, 'Kettinge');
INSERT INTO ZIPCITY
VALUES
	(4894, 'Øster Ulslev');
INSERT INTO ZIPCITY
VALUES
	(4895, 'Errindlev');
INSERT INTO ZIPCITY
VALUES
	(4900, 'Nakskov');
INSERT INTO ZIPCITY
VALUES
	(4912, 'Harpelunde');
INSERT INTO ZIPCITY
VALUES
	(4913, 'Horslunde');
INSERT INTO ZIPCITY
VALUES
	(4920, 'Søllested');
INSERT INTO ZIPCITY
VALUES
	(4930, 'Maribo');
INSERT INTO ZIPCITY
VALUES
	(4941, 'Bandholm');
INSERT INTO ZIPCITY
VALUES
	(4942, 'Askø og Lilleø');
INSERT INTO ZIPCITY
VALUES
	(4943, 'Torrig L');
INSERT INTO ZIPCITY
VALUES
	(4944, 'Fejø');
INSERT INTO ZIPCITY
VALUES
	(4945, 'Femø');
INSERT INTO ZIPCITY
VALUES
	(4951, 'Nørreballe');
INSERT INTO ZIPCITY
VALUES
	(4952, 'Stokkemarke');
INSERT INTO ZIPCITY
VALUES
	(4953, 'Vesterborg');
INSERT INTO ZIPCITY
VALUES
	(4960, 'Holeby');
INSERT INTO ZIPCITY
VALUES
	(4970, 'Rødby');
INSERT INTO ZIPCITY
VALUES
	(4983, 'Dannemare');
INSERT INTO ZIPCITY
VALUES
	(4990, 'Sakskøbing');
INSERT INTO ZIPCITY
VALUES
	(5000, 'Odense C');
INSERT INTO ZIPCITY
VALUES
	(5200, 'Odense V');
INSERT INTO ZIPCITY
VALUES
	(5210, 'Odense NV');
INSERT INTO ZIPCITY
VALUES
	(5220, 'Odense SØ');
INSERT INTO ZIPCITY
VALUES
	(5230, 'Odense M');
INSERT INTO ZIPCITY
VALUES
	(5240, 'Odense NØ');
INSERT INTO ZIPCITY
VALUES
	(5250, 'Odense SV');
INSERT INTO ZIPCITY
VALUES
	(5260, 'Odense S');
INSERT INTO ZIPCITY
VALUES
	(5270, 'Odense N');
INSERT INTO ZIPCITY
VALUES
	(5290, 'Marslev');
INSERT INTO ZIPCITY
VALUES
	(5300, 'Kerteminde');
INSERT INTO ZIPCITY
VALUES
	(5320, 'Agedrup');
INSERT INTO ZIPCITY
VALUES
	(5330, 'Munkebo');
INSERT INTO ZIPCITY
VALUES
	(5350, 'Rynkeby');
INSERT INTO ZIPCITY
VALUES
	(5370, 'Mesinge');
INSERT INTO ZIPCITY
VALUES
	(5380, 'Dalby');
INSERT INTO ZIPCITY
VALUES
	(5390, 'Martofte');
INSERT INTO ZIPCITY
VALUES
	(5400, 'Bogense');
INSERT INTO ZIPCITY
VALUES
	(5450, 'Otterup');
INSERT INTO ZIPCITY
VALUES
	(5462, 'Morud');
INSERT INTO ZIPCITY
VALUES
	(5463, 'Harndrup');
INSERT INTO ZIPCITY
VALUES
	(5464, 'Brenderup Fyn');
INSERT INTO ZIPCITY
VALUES
	(5466, 'Asperup');
INSERT INTO ZIPCITY
VALUES
	(5471, 'Søndersø');
INSERT INTO ZIPCITY
VALUES
	(5474, 'Veflinge');
INSERT INTO ZIPCITY
VALUES
	(5485, 'Skamby');
INSERT INTO ZIPCITY
VALUES
	(5491, 'Blommenslyst');
INSERT INTO ZIPCITY
VALUES
	(5492, 'Vissenbjerg');
INSERT INTO ZIPCITY
VALUES
	(5500, 'Middelfart');
INSERT INTO ZIPCITY
VALUES
	(5540, 'Ullerslev');
INSERT INTO ZIPCITY
VALUES
	(5550, 'Langeskov');
INSERT INTO ZIPCITY
VALUES
	(5560, 'Aarup');
INSERT INTO ZIPCITY
VALUES
	(5580, 'Nørre Aaby');
INSERT INTO ZIPCITY
VALUES
	(5591, 'Gelsted');
INSERT INTO ZIPCITY
VALUES
	(5592, 'Ejby');
INSERT INTO ZIPCITY
VALUES
	(5600, 'Faaborg');
INSERT INTO ZIPCITY
VALUES
	(5601, 'Lyø');
INSERT INTO ZIPCITY
VALUES
	(5602, 'Avernakø');
INSERT INTO ZIPCITY
VALUES
	(5603, 'Bjørnø');
INSERT INTO ZIPCITY
VALUES
	(5610, 'Assens');
INSERT INTO ZIPCITY
VALUES
	(5620, 'Glamsbjerg');
INSERT INTO ZIPCITY
VALUES
	(5631, 'Ebberup');
INSERT INTO ZIPCITY
VALUES
	(5642, 'Millinge');
INSERT INTO ZIPCITY
VALUES
	(5672, 'Broby');
INSERT INTO ZIPCITY
VALUES
	(5683, 'Haarby');
INSERT INTO ZIPCITY
VALUES
	(5690, 'Tommerup');
INSERT INTO ZIPCITY
VALUES
	(5700, 'Svendborg');
INSERT INTO ZIPCITY
VALUES
	(5750, 'Ringe');
INSERT INTO ZIPCITY
VALUES
	(5762, 'Vester Skerninge');
INSERT INTO ZIPCITY
VALUES
	(5771, 'Stenstrup');
INSERT INTO ZIPCITY
VALUES
	(5772, 'Kværndrup');
INSERT INTO ZIPCITY
VALUES
	(5792, 'Årslev');
INSERT INTO ZIPCITY
VALUES
	(5800, 'Nyborg');
INSERT INTO ZIPCITY
VALUES
	(5853, 'Ørbæk');
INSERT INTO ZIPCITY
VALUES
	(5854, 'Gislev');
INSERT INTO ZIPCITY
VALUES
	(5856, 'Ryslinge');
INSERT INTO ZIPCITY
VALUES
	(5863, 'Ferritslev Fyn');
INSERT INTO ZIPCITY
VALUES
	(5871, 'Frørup');
INSERT INTO ZIPCITY
VALUES
	(5874, 'Hesselager');
INSERT INTO ZIPCITY
VALUES
	(5881, 'Skårup Fyn');
INSERT INTO ZIPCITY
VALUES
	(5882, 'Vejstrup');
INSERT INTO ZIPCITY
VALUES
	(5883, 'Oure');
INSERT INTO ZIPCITY
VALUES
	(5884, 'Gudme');
INSERT INTO ZIPCITY
VALUES
	(5892, 'Gudbjerg Sydfyn');
INSERT INTO ZIPCITY
VALUES
	(5900, 'Rudkøbing');
INSERT INTO ZIPCITY
VALUES
	(5932, 'Humble');
INSERT INTO ZIPCITY
VALUES
	(5935, 'Bagenkop');
INSERT INTO ZIPCITY
VALUES
	(5943, 'Strynø');
INSERT INTO ZIPCITY
VALUES
	(5953, 'Tranekær');
INSERT INTO ZIPCITY
VALUES
	(5960, 'Marstal');
INSERT INTO ZIPCITY
VALUES
	(5965, 'Birkholm');
INSERT INTO ZIPCITY
VALUES
	(5970, 'Ærøskøbing');
INSERT INTO ZIPCITY
VALUES
	(5985, 'Søby Ærø');
INSERT INTO ZIPCITY
VALUES
	(6000, 'Kolding');
INSERT INTO ZIPCITY
VALUES
	(6040, 'Egtved');
INSERT INTO ZIPCITY
VALUES
	(6051, 'Almind');
INSERT INTO ZIPCITY
VALUES
	(6052, 'Viuf');
INSERT INTO ZIPCITY
VALUES
	(6064, 'Jordrup');
INSERT INTO ZIPCITY
VALUES
	(6070, 'Christiansfeld');
INSERT INTO ZIPCITY
VALUES
	(6091, 'Bjert');
INSERT INTO ZIPCITY
VALUES
	(6092, 'Sønder Stenderup');
INSERT INTO ZIPCITY
VALUES
	(6093, 'Sjølund');
INSERT INTO ZIPCITY
VALUES
	(6094, 'Hejls');
INSERT INTO ZIPCITY
VALUES
	(6100, 'Haderslev');
INSERT INTO ZIPCITY
VALUES
	(6200, 'Aabenraa');
INSERT INTO ZIPCITY
VALUES
	(6210, 'Barsø');
INSERT INTO ZIPCITY
VALUES
	(6230, 'Rødekro');
INSERT INTO ZIPCITY
VALUES
	(6240, 'Løgumkloster');
INSERT INTO ZIPCITY
VALUES
	(6261, 'Bredebro');
INSERT INTO ZIPCITY
VALUES
	(6270, 'Tønder');
INSERT INTO ZIPCITY
VALUES
	(6280, 'Højer');
INSERT INTO ZIPCITY
VALUES
	(6300, 'Gråsten');
INSERT INTO ZIPCITY
VALUES
	(6310, 'Broager');
INSERT INTO ZIPCITY
VALUES
	(6320, 'Egernsund');
INSERT INTO ZIPCITY
VALUES
	(6330, 'Padborg');
INSERT INTO ZIPCITY
VALUES
	(6340, 'Kruså');
INSERT INTO ZIPCITY
VALUES
	(6360, 'Tinglev');
INSERT INTO ZIPCITY
VALUES
	(6372, 'Bylderup-Bov');
INSERT INTO ZIPCITY
VALUES
	(6392, 'Bolderslev');
INSERT INTO ZIPCITY
VALUES
	(6400, 'Sønderborg');
INSERT INTO ZIPCITY
VALUES
	(6430, 'Nordborg');
INSERT INTO ZIPCITY
VALUES
	(6440, 'Augustenborg');
INSERT INTO ZIPCITY
VALUES
	(6470, 'Sydals');
INSERT INTO ZIPCITY
VALUES
	(6500, 'Vojens');
INSERT INTO ZIPCITY
VALUES
	(6510, 'Gram');
INSERT INTO ZIPCITY
VALUES
	(6520, 'Toftlund');
INSERT INTO ZIPCITY
VALUES
	(6534, 'Agerskov');
INSERT INTO ZIPCITY
VALUES
	(6535, 'Branderup J');
INSERT INTO ZIPCITY
VALUES
	(6541, 'Bevtoft');
INSERT INTO ZIPCITY
VALUES
	(6560, 'Sommersted');
INSERT INTO ZIPCITY
VALUES
	(6580, 'Vamdrup');
INSERT INTO ZIPCITY
VALUES
	(6600, 'Vejen');
INSERT INTO ZIPCITY
VALUES
	(6621, 'Gesten');
INSERT INTO ZIPCITY
VALUES
	(6622, 'Bække');
INSERT INTO ZIPCITY
VALUES
	(6623, 'Vorbasse');
INSERT INTO ZIPCITY
VALUES
	(6630, 'Rødding');
INSERT INTO ZIPCITY
VALUES
	(6640, 'Lunderskov');
INSERT INTO ZIPCITY
VALUES
	(6650, 'Brørup');
INSERT INTO ZIPCITY
VALUES
	(6660, 'Lintrup');
INSERT INTO ZIPCITY
VALUES
	(6670, 'Holsted');
INSERT INTO ZIPCITY
VALUES
	(6682, 'Hovborg');
INSERT INTO ZIPCITY
VALUES
	(6683, 'Føvling');
INSERT INTO ZIPCITY
VALUES
	(6690, 'Gørding');
INSERT INTO ZIPCITY
VALUES
	(6700, 'Esbjerg');
INSERT INTO ZIPCITY
VALUES
	(6705, 'Esbjerg Ø');
INSERT INTO ZIPCITY
VALUES
	(6710, 'Esbjerg V');
INSERT INTO ZIPCITY
VALUES
	(6715, 'Esbjerg N');
INSERT INTO ZIPCITY
VALUES
	(6720, 'Fanø');
INSERT INTO ZIPCITY
VALUES
	(6731, 'Tjæreborg');
INSERT INTO ZIPCITY
VALUES
	(6740, 'Bramming');
INSERT INTO ZIPCITY
VALUES
	(6752, 'Glejbjerg');
INSERT INTO ZIPCITY
VALUES
	(6753, 'Agerbæk');
INSERT INTO ZIPCITY
VALUES
	(6760, 'Ribe');
INSERT INTO ZIPCITY
VALUES
	(6771, 'Gredstedbro');
INSERT INTO ZIPCITY
VALUES
	(6780, 'Skærbæk');
INSERT INTO ZIPCITY
VALUES
	(6792, 'Rømø');
INSERT INTO ZIPCITY
VALUES
	(6800, 'Varde');
INSERT INTO ZIPCITY
VALUES
	(6818, 'Årre');
INSERT INTO ZIPCITY
VALUES
	(6823, 'Ansager');
INSERT INTO ZIPCITY
VALUES
	(6830, 'Nørre Nebel');
INSERT INTO ZIPCITY
VALUES
	(6840, 'Oksbøl');
INSERT INTO ZIPCITY
VALUES
	(6851, 'Janderup Vestj');
INSERT INTO ZIPCITY
VALUES
	(6852, 'Billum');
INSERT INTO ZIPCITY
VALUES
	(6853, 'Vejers Strand');
INSERT INTO ZIPCITY
VALUES
	(6854, 'Henne');
INSERT INTO ZIPCITY
VALUES
	(6855, 'Outrup');
INSERT INTO ZIPCITY
VALUES
	(6857, 'Blåvand');
INSERT INTO ZIPCITY
VALUES
	(6862, 'Tistrup');
INSERT INTO ZIPCITY
VALUES
	(6870, 'Ølgod');
INSERT INTO ZIPCITY
VALUES
	(6880, 'Tarm');
INSERT INTO ZIPCITY
VALUES
	(6893, 'Hemmet');
INSERT INTO ZIPCITY
VALUES
	(6900, 'Skjern');
INSERT INTO ZIPCITY
VALUES
	(6920, 'Videbæk');
INSERT INTO ZIPCITY
VALUES
	(6933, 'Kibæk');
INSERT INTO ZIPCITY
VALUES
	(6940, 'Lem St');
INSERT INTO ZIPCITY
VALUES
	(6950, 'Ringkøbing');
INSERT INTO ZIPCITY
VALUES
	(6960, 'Hvide Sande');
INSERT INTO ZIPCITY
VALUES
	(6971, 'Spjald');
INSERT INTO ZIPCITY
VALUES
	(6973, 'Ørnhøj');
INSERT INTO ZIPCITY
VALUES
	(6980, 'Tim');
INSERT INTO ZIPCITY
VALUES
	(6990, 'Ulfborg');
INSERT INTO ZIPCITY
VALUES
	(7000, 'Fredericia');
INSERT INTO ZIPCITY
VALUES
	(7080, 'Børkop');
INSERT INTO ZIPCITY
VALUES
	(7100, 'Vejle');
INSERT INTO ZIPCITY
VALUES
	(7120, 'Vejle Øst');
INSERT INTO ZIPCITY
VALUES
	(7130, 'Juelsminde');
INSERT INTO ZIPCITY
VALUES
	(7140, 'Stouby');
INSERT INTO ZIPCITY
VALUES
	(7150, 'Barrit');
INSERT INTO ZIPCITY
VALUES
	(7160, 'Tørring');
INSERT INTO ZIPCITY
VALUES
	(7171, 'Uldum');
INSERT INTO ZIPCITY
VALUES
	(7173, 'Vonge');
INSERT INTO ZIPCITY
VALUES
	(7182, 'Bredsten');
INSERT INTO ZIPCITY
VALUES
	(7183, 'Randbøl');
INSERT INTO ZIPCITY
VALUES
	(7184, 'Vandel');
INSERT INTO ZIPCITY
VALUES
	(7190, 'Billund');
INSERT INTO ZIPCITY
VALUES
	(7200, 'Grindsted');
INSERT INTO ZIPCITY
VALUES
	(7250, 'Hejnsvig');
INSERT INTO ZIPCITY
VALUES
	(7260, 'Sønder Omme');
INSERT INTO ZIPCITY
VALUES
	(7270, 'Stakroge');
INSERT INTO ZIPCITY
VALUES
	(7280, 'Sønder Felding');
INSERT INTO ZIPCITY
VALUES
	(7300, 'Jelling');
INSERT INTO ZIPCITY
VALUES
	(7321, 'Gadbjerg');
INSERT INTO ZIPCITY
VALUES
	(7323, 'Give');
INSERT INTO ZIPCITY
VALUES
	(7330, 'Brande');
INSERT INTO ZIPCITY
VALUES
	(7361, 'Ejstrupholm');
INSERT INTO ZIPCITY
VALUES
	(7362, 'Hampen');
INSERT INTO ZIPCITY
VALUES
	(7400, 'Herning');
INSERT INTO ZIPCITY
VALUES
	(7430, 'Ikast');
INSERT INTO ZIPCITY
VALUES
	(7441, 'Bording');
INSERT INTO ZIPCITY
VALUES
	(7442, 'Engesvang');
INSERT INTO ZIPCITY
VALUES
	(7451, 'Sunds');
INSERT INTO ZIPCITY
VALUES
	(7470, 'Karup J');
INSERT INTO ZIPCITY
VALUES
	(7480, 'Vildbjerg');
INSERT INTO ZIPCITY
VALUES
	(7490, 'Aulum');
INSERT INTO ZIPCITY
VALUES
	(7500, 'Holstebro');
INSERT INTO ZIPCITY
VALUES
	(7540, 'Haderup');
INSERT INTO ZIPCITY
VALUES
	(7550, 'Sørvad');
INSERT INTO ZIPCITY
VALUES
	(7560, 'Hjerm');
INSERT INTO ZIPCITY
VALUES
	(7570, 'Vemb');
INSERT INTO ZIPCITY
VALUES
	(7600, 'Struer');
INSERT INTO ZIPCITY
VALUES
	(7620, 'Lemvig');
INSERT INTO ZIPCITY
VALUES
	(7650, 'Bøvlingbjerg');
INSERT INTO ZIPCITY
VALUES
	(7660, 'Bækmarksbro');
INSERT INTO ZIPCITY
VALUES
	(7673, 'Harboøre');
INSERT INTO ZIPCITY
VALUES
	(7680, 'Thyborøn');
INSERT INTO ZIPCITY
VALUES
	(7700, 'Thisted');
INSERT INTO ZIPCITY
VALUES
	(7730, 'Hanstholm');
INSERT INTO ZIPCITY
VALUES
	(7741, 'Frøstrup');
INSERT INTO ZIPCITY
VALUES
	(7742, 'Vesløs');
INSERT INTO ZIPCITY
VALUES
	(7752, 'Snedsted');
INSERT INTO ZIPCITY
VALUES
	(7755, 'Bedsted Thy');
INSERT INTO ZIPCITY
VALUES
	(7760, 'Hurup Thy');
INSERT INTO ZIPCITY
VALUES
	(7770, 'Vestervig');
INSERT INTO ZIPCITY
VALUES
	(7790, 'Thyholm');
INSERT INTO ZIPCITY
VALUES
	(7800, 'Skive');
INSERT INTO ZIPCITY
VALUES
	(7830, 'Vinderup');
INSERT INTO ZIPCITY
VALUES
	(7840, 'Højslev');
INSERT INTO ZIPCITY
VALUES
	(7850, 'Stoholm Jyll');
INSERT INTO ZIPCITY
VALUES
	(7860, 'Spøttrup');
INSERT INTO ZIPCITY
VALUES
	(7870, 'Roslev');
INSERT INTO ZIPCITY
VALUES
	(7884, 'Fur');
INSERT INTO ZIPCITY
VALUES
	(7900, 'Nykøbing M');
INSERT INTO ZIPCITY
VALUES
	(7950, 'Erslev');
INSERT INTO ZIPCITY
VALUES
	(7960, 'Karby');
INSERT INTO ZIPCITY
VALUES
	(7970, 'Redsted M');
INSERT INTO ZIPCITY
VALUES
	(7980, 'Vils');
INSERT INTO ZIPCITY
VALUES
	(7990, 'Øster Assels');
INSERT INTO ZIPCITY
VALUES
	(8000, 'Aarhus C');
INSERT INTO ZIPCITY
VALUES
	(8200, 'Aarhus N');
INSERT INTO ZIPCITY
VALUES
	(8210, 'Aarhus V');
INSERT INTO ZIPCITY
VALUES
	(8220, 'Brabrand');
INSERT INTO ZIPCITY
VALUES
	(8230, 'Åbyhøj');
INSERT INTO ZIPCITY
VALUES
	(8240, 'Risskov');
INSERT INTO ZIPCITY
VALUES
	(8250, 'Egå');
INSERT INTO ZIPCITY
VALUES
	(8260, 'Viby J');
INSERT INTO ZIPCITY
VALUES
	(8270, 'Højbjerg');
INSERT INTO ZIPCITY
VALUES
	(8300, 'Odder');
INSERT INTO ZIPCITY
VALUES
	(8305, 'Samsø');
INSERT INTO ZIPCITY
VALUES
	(8310, 'Tranbjerg J');
INSERT INTO ZIPCITY
VALUES
	(8320, 'Mårslet');
INSERT INTO ZIPCITY
VALUES
	(8330, 'Beder');
INSERT INTO ZIPCITY
VALUES
	(8340, 'Malling');
INSERT INTO ZIPCITY
VALUES
	(8350, 'Hundslund');
INSERT INTO ZIPCITY
VALUES
	(8355, 'Solbjerg');
INSERT INTO ZIPCITY
VALUES
	(8361, 'Hasselager');
INSERT INTO ZIPCITY
VALUES
	(8362, 'Hørning');
INSERT INTO ZIPCITY
VALUES
	(8370, 'Hadsten');
INSERT INTO ZIPCITY
VALUES
	(8380, 'Trige');
INSERT INTO ZIPCITY
VALUES
	(8381, 'Tilst');
INSERT INTO ZIPCITY
VALUES
	(8382, 'Hinnerup');
INSERT INTO ZIPCITY
VALUES
	(8400, 'Ebeltoft');
INSERT INTO ZIPCITY
VALUES
	(8410, 'Rønde');
INSERT INTO ZIPCITY
VALUES
	(8420, 'Knebel');
INSERT INTO ZIPCITY
VALUES
	(8444, 'Balle');
INSERT INTO ZIPCITY
VALUES
	(8450, 'Hammel');
INSERT INTO ZIPCITY
VALUES
	(8462, 'Harlev J');
INSERT INTO ZIPCITY
VALUES
	(8464, 'Galten');
INSERT INTO ZIPCITY
VALUES
	(8471, 'Sabro');
INSERT INTO ZIPCITY
VALUES
	(8472, 'Sporup');
INSERT INTO ZIPCITY
VALUES
	(8500, 'Grenaa');
INSERT INTO ZIPCITY
VALUES
	(8520, 'Lystrup');
INSERT INTO ZIPCITY
VALUES
	(8530, 'Hjortshøj');
INSERT INTO ZIPCITY
VALUES
	(8541, 'Skødstrup');
INSERT INTO ZIPCITY
VALUES
	(8543, 'Hornslet');
INSERT INTO ZIPCITY
VALUES
	(8544, 'Mørke');
INSERT INTO ZIPCITY
VALUES
	(8550, 'Ryomgård');
INSERT INTO ZIPCITY
VALUES
	(8560, 'Kolind');
INSERT INTO ZIPCITY
VALUES
	(8570, 'Trustrup');
INSERT INTO ZIPCITY
VALUES
	(8581, 'Nimtofte');
INSERT INTO ZIPCITY
VALUES
	(8585, 'Glesborg');
INSERT INTO ZIPCITY
VALUES
	(8586, 'Ørum Djurs');
INSERT INTO ZIPCITY
VALUES
	(8592, 'Anholt');
INSERT INTO ZIPCITY
VALUES
	(8600, 'Silkeborg');
INSERT INTO ZIPCITY
VALUES
	(8620, 'Kjellerup');
INSERT INTO ZIPCITY
VALUES
	(8632, 'Lemming');
INSERT INTO ZIPCITY
VALUES
	(8641, 'Sorring');
INSERT INTO ZIPCITY
VALUES
	(8643, 'Ans By');
INSERT INTO ZIPCITY
VALUES
	(8653, 'Them');
INSERT INTO ZIPCITY
VALUES
	(8654, 'Bryrup');
INSERT INTO ZIPCITY
VALUES
	(8660, 'Skanderborg');
INSERT INTO ZIPCITY
VALUES
	(8670, 'Låsby');
INSERT INTO ZIPCITY
VALUES
	(8680, 'Ry');
INSERT INTO ZIPCITY
VALUES
	(8700, 'Horsens');
INSERT INTO ZIPCITY
VALUES
	(8721, 'Daugård');
INSERT INTO ZIPCITY
VALUES
	(8722, 'Hedensted');
INSERT INTO ZIPCITY
VALUES
	(8723, 'Løsning');
INSERT INTO ZIPCITY
VALUES
	(8732, 'Hovedgård');
INSERT INTO ZIPCITY
VALUES
	(8740, 'Brædstrup');
INSERT INTO ZIPCITY
VALUES
	(8751, 'Gedved');
INSERT INTO ZIPCITY
VALUES
	(8752, 'Østbirk');
INSERT INTO ZIPCITY
VALUES
	(8762, 'Flemming');
INSERT INTO ZIPCITY
VALUES
	(8763, 'Rask Mølle');
INSERT INTO ZIPCITY
VALUES
	(8765, 'Klovborg');
INSERT INTO ZIPCITY
VALUES
	(8766, 'Nørre Snede');
INSERT INTO ZIPCITY
VALUES
	(8781, 'Stenderup');
INSERT INTO ZIPCITY
VALUES
	(8783, 'Hornsyld');
INSERT INTO ZIPCITY
VALUES
	(8789, 'Endelave');
INSERT INTO ZIPCITY
VALUES
	(8799, 'Tunø');
INSERT INTO ZIPCITY
VALUES
	(8800, 'Viborg');
INSERT INTO ZIPCITY
VALUES
	(8830, 'Tjele');
INSERT INTO ZIPCITY
VALUES
	(8831, 'Løgstrup');
INSERT INTO ZIPCITY
VALUES
	(8832, 'Skals');
INSERT INTO ZIPCITY
VALUES
	(8840, 'Rødkærsbro');
INSERT INTO ZIPCITY
VALUES
	(8850, 'Bjerringbro');
INSERT INTO ZIPCITY
VALUES
	(8860, 'Ulstrup');
INSERT INTO ZIPCITY
VALUES
	(8870, 'Langå');
INSERT INTO ZIPCITY
VALUES
	(8881, 'Thorsø');
INSERT INTO ZIPCITY
VALUES
	(8882, 'Fårvang');
INSERT INTO ZIPCITY
VALUES
	(8883, 'Gjern');
INSERT INTO ZIPCITY
VALUES
	(8900, 'Randers C');
INSERT INTO ZIPCITY
VALUES
	(8920, 'Randers NV');
INSERT INTO ZIPCITY
VALUES
	(8930, 'Randers NØ');
INSERT INTO ZIPCITY
VALUES
	(8940, 'Randers SV');
INSERT INTO ZIPCITY
VALUES
	(8950, 'Ørsted');
INSERT INTO ZIPCITY
VALUES
	(8960, 'Randers SØ');
INSERT INTO ZIPCITY
VALUES
	(8961, 'Allingåbro');
INSERT INTO ZIPCITY
VALUES
	(8963, 'Auning');
INSERT INTO ZIPCITY
VALUES
	(8970, 'Havndal');
INSERT INTO ZIPCITY
VALUES
	(8981, 'Spentrup');
INSERT INTO ZIPCITY
VALUES
	(8983, 'Gjerlev J');
INSERT INTO ZIPCITY
VALUES
	(8990, 'Fårup');
INSERT INTO ZIPCITY
VALUES
	(9000, 'Aalborg');
INSERT INTO ZIPCITY
VALUES
	(9200, 'Aalborg SV');
INSERT INTO ZIPCITY
VALUES
	(9210, 'Aalborg SØ');
INSERT INTO ZIPCITY
VALUES
	(9220, 'Aalborg Øst');
INSERT INTO ZIPCITY
VALUES
	(9230, 'Svenstrup J');
INSERT INTO ZIPCITY
VALUES
	(9240, 'Nibe');
INSERT INTO ZIPCITY
VALUES
	(9260, 'Gistrup');
INSERT INTO ZIPCITY
VALUES
	(9270, 'Klarup');
INSERT INTO ZIPCITY
VALUES
	(9280, 'Storvorde');
INSERT INTO ZIPCITY
VALUES
	(9293, 'Kongerslev');
INSERT INTO ZIPCITY
VALUES
	(9300, 'Sæby');
INSERT INTO ZIPCITY
VALUES
	(9310, 'Vodskov');
INSERT INTO ZIPCITY
VALUES
	(9320, 'Hjallerup');
INSERT INTO ZIPCITY
VALUES
	(9330, 'Dronninglund');
INSERT INTO ZIPCITY
VALUES
	(9340, 'Asaa');
INSERT INTO ZIPCITY
VALUES
	(9352, 'Dybvad');
INSERT INTO ZIPCITY
VALUES
	(9362, 'Gandrup');
INSERT INTO ZIPCITY
VALUES
	(9370, 'Hals');
INSERT INTO ZIPCITY
VALUES
	(9380, 'Vestbjerg');
INSERT INTO ZIPCITY
VALUES
	(9381, 'Sulsted');
INSERT INTO ZIPCITY
VALUES
	(9382, 'Tylstrup');
INSERT INTO ZIPCITY
VALUES
	(9400, 'Nørresundby');
INSERT INTO ZIPCITY
VALUES
	(9430, 'Vadum');
INSERT INTO ZIPCITY
VALUES
	(9440, 'Aabybro');
INSERT INTO ZIPCITY
VALUES
	(9460, 'Brovst');
INSERT INTO ZIPCITY
VALUES
	(9480, 'Løkken');
INSERT INTO ZIPCITY
VALUES
	(9490, 'Pandrup');
INSERT INTO ZIPCITY
VALUES
	(9492, 'Blokhus');
INSERT INTO ZIPCITY
VALUES
	(9493, 'Saltum');
INSERT INTO ZIPCITY
VALUES
	(9500, 'Hobro');
INSERT INTO ZIPCITY
VALUES
	(9510, 'Arden');
INSERT INTO ZIPCITY
VALUES
	(9520, 'Skørping');
INSERT INTO ZIPCITY
VALUES
	(9530, 'Støvring');
INSERT INTO ZIPCITY
VALUES
	(9541, 'Suldrup');
INSERT INTO ZIPCITY
VALUES
	(9550, 'Mariager');
INSERT INTO ZIPCITY
VALUES
	(9560, 'Hadsund');
INSERT INTO ZIPCITY
VALUES
	(9574, 'Bælum');
INSERT INTO ZIPCITY
VALUES
	(9575, 'Terndrup');
INSERT INTO ZIPCITY
VALUES
	(9600, 'Aars');
INSERT INTO ZIPCITY
VALUES
	(9610, 'Nørager');
INSERT INTO ZIPCITY
VALUES
	(9620, 'Aalestrup');
INSERT INTO ZIPCITY
VALUES
	(9631, 'Gedsted');
INSERT INTO ZIPCITY
VALUES
	(9632, 'Møldrup');
INSERT INTO ZIPCITY
VALUES
	(9640, 'Farsø');
INSERT INTO ZIPCITY
VALUES
	(9670, 'Løgstør');
INSERT INTO ZIPCITY
VALUES
	(9681, 'Ranum');
INSERT INTO ZIPCITY
VALUES
	(9690, 'Fjerritslev');
INSERT INTO ZIPCITY
VALUES
	(9700, 'Brønderslev');
INSERT INTO ZIPCITY
VALUES
	(9740, 'Jerslev J');
INSERT INTO ZIPCITY
VALUES
	(9750, 'Østervrå');
INSERT INTO ZIPCITY
VALUES
	(9760, 'Vrå');
INSERT INTO ZIPCITY
VALUES
	(9800, 'Hjørring');
INSERT INTO ZIPCITY
VALUES
	(9830, 'Tårs');
INSERT INTO ZIPCITY
VALUES
	(9850, 'Hirtshals');
INSERT INTO ZIPCITY
VALUES
	(9870, 'Sindal');
INSERT INTO ZIPCITY
VALUES
	(9881, 'Bindslev');
INSERT INTO ZIPCITY
VALUES
	(9900, 'Frederikshavn');
INSERT INTO ZIPCITY
VALUES
	(9940, 'Læsø');
INSERT INTO ZIPCITY
VALUES
	(9970, 'Strandby');
INSERT INTO ZIPCITY
VALUES
	(9981, 'Jerup');
INSERT INTO ZIPCITY
VALUES
	(9982, 'Ålbæk');
INSERT INTO ZIPCITY
VALUES
	(9990, 'Skagen');

ALTER TABLE ZIPCITY ADD LastChanged rowversion;

--INSERT INTO CATEGORY 

INSERT INTO CATEGORY
VALUES('CPU');

INSERT INTO CATEGORY
VALUES('GPU');

INSERT INTO CATEGORY
VALUES('STRØMFORSYNING');

INSERT INTO CATEGORY
VALUES('RAM');

INSERT INTO CATEGORY
VALUES('BLÆSER')

INSERT INTO CATEGORY
VALUES('BUNDKORT')

INSERT INTO CATEGORY
VALUES('KABINET')

INSERT INTO CATEGORY
VALUES('CPULUFTKØLER')

INSERT INTO CATEGORY
VALUES('CPUVANDKØLER')

INSERT INTO CATEGORY
VALUES('HDD')

INSERT INTO CATEGORY
VALUES('SSD')

INSERT INTO CATEGORY
VALUES('MUS')

INSERT INTO CATEGORY
VALUES('SKÆRME')

INSERT INTO CATEGORY
VALUES('TASTATUR')

INSERT INTO CATEGORY
VALUES('KABLER')

INSERT INTO CATEGORY
VALUES('NETKORT')

INSERT INTO CATEGORY
VALUES('LYDKORT')

INSERT INTO CATEGORY
VALUES('HEADSET')




ALTER TABLE Category ADD LastChanged rowversion;

--INSERT INTO SUPPLIER

INSERT INTO SUPPLIER
VALUES('ASUS', 'US', '89541078', '20364875', 'support@asus.com');

INSERT INTO SUPPLIER
VALUES('MSI', 'DK', '47530158', '30147856', 'support@msi.dk');

INSERT INTO SUPPLIER
VALUES('INTEL', 'UK', '47865109', '40585203', 'support@intel.co.uk');

INSERT INTO SUPPLIER
VALUES('HYPER X', 'DE', '14523697', '56987025', 'support@hyperx.de');

INSERT INTO SUPPLIER
VALUES('CORSAIR', 'IT', '69875204', '62048604', 'support@corsair.it');

INSERT INTO SUPPLIER
VALUES('SAMSUNG', 'AU', '98652037', '78501259', 'support@samsung.au');

INSERT INTO SUPPLIER
VALUES('STEELSERIES', 'PL', '87658952', '89478505', 'support@steelseries.pl');

INSERT INTO SUPPLIER
VALUES('RAZER', 'RU', '65890146', '95870268', 'support@razer.ru');

INSERT INTO SUPPLIER
VALUES('NOCTUA', 'NO', '77658920', '22064795', 'support@noctua.no');

INSERT INTO SUPPLIER
VALUES('AMD', 'SE', '65901358', '36014589', 'support@amd.se');

INSERT INTO SUPPLIER
VALUES('CRYORIG', 'BE', '47853695', '48601579', 'support@cryorig.be');

INSERT INTO SUPPLIER
VALUES('NZXT', 'CA', '56203158', '59201458', 'support@nzxt.ca');

INSERT INTO SUPPLIER
VALUES('SEAGATE', 'FI', '65369208', '63014589', 'support@seagate.fi');

INSERT INTO SUPPLIER
VALUES('IIGLO', 'CZ', '47852036', '74102365', 'support@iiglo.cz');

INSERT INTO SUPPLIER
VALUES('EVGA', 'LU', '87602135', '80265975', 'support@evga.lu');

INSERT INTO SUPPLIER
VALUES('COOLER MASTER', 'CN', '65890245', '690125678', 'support@coolermaster.cn');

INSERT INTO SUPPLIER
VALUES('KINGSTON', 'CH', '58960658', '36901237', 'support@kingston.ch');

ALTER TABLE SUPPLIER ADD LastChanged rowversion;

--INSERT INTO CUSTOMER
INSERT INTO CUSTOMER
VALUES('Casper', 'Pedersen', 'casppedersen542@outlook.com', 'Vangen 520', '69875124', (SELECT id
		FROM ZIPCITY
		WHERE zipCode = '9000'));

INSERT INTO CUSTOMER
VALUES('Mikkel', 'Andersen', 'mikndersen18267@hotmail.dk', 'Langgade 5', '45216980', (SELECT id
		FROM ZIPCITY
		WHERE zipCode = '5500'));

INSERT INTO CUSTOMER
VALUES('Kent', 'Nielsen', 'kenielsen456@gmail.co.uk', 'Svinget 20', '25634897', (SELECT id
		FROM ZIPCITY
		WHERE zipCode = '9200'));

INSERT INTO CUSTOMER
VALUES('Bo', 'Jensen', 'bojensen12384@gmail.de', 'Hovedgaden 2', '12457964', (SELECT id
		FROM ZIPCITY
		WHERE zipCode = '9000'));

INSERT INTO CUSTOMER
VALUES('Peter', 'Holm', 'ptrhm4850@gmail.de', 'Vænget 22', '87542100', (SELECT id
		FROM ZIPCITY
		WHERE zipCode = '9990'));

INSERT INTO CUSTOMER
VALUES('Mads', 'Jørgensen', 'madsjørg5687@outlook.com', 'Blokken 22B', '45862307', (SELECT id
		FROM ZIPCITY
		WHERE zipCode = '1450'));

INSERT INTO CUSTOMER
VALUES('Martin', 'Jørgensen', 'marjørg5687@outlook.com', 'Blokken 22B', '87601597', (SELECT id
		FROM ZIPCITY
		WHERE zipCode = '1460'));


ALTER TABLE CUSTOMER ADD LastChanged rowversion;

--INSERT INTO MYORDER
INSERT INTO MYORDER
VALUES('1', '1', (SELECT id
		FROM CUSTOMER
		WHERE id = '1'));

INSERT INTO MYORDER
VALUES('0', '1', (SELECT id
		FROM CUSTOMER
		WHERE id = '2'));

INSERT INTO MYORDER
VALUES('1', '0', (SELECT id
		FROM CUSTOMER
		WHERE id = '3'));

INSERT INTO MYORDER
VALUES('0', '0', (SELECT id
		FROM CUSTOMER
		WHERE id = '4'));

INSERT INTO MYORDER
VALUES('1', '0', (SELECT id
		FROM CUSTOMER
		WHERE id = '5'));

INSERT INTO MYORDER
VALUES('1', '1', (SELECT id
		FROM CUSTOMER
		WHERE id = '6'));

INSERT INTO MYORDER
VALUES('0', '1', (SELECT id
		FROM CUSTOMER
		WHERE id = '7'));

ALTER TABLE MYORDER ADD LastChanged rowversion;

--INSERT INTO PRODUCT
INSERT INTO PRODUCT
VALUES('Asus GeForce DUAL RTX 2080 O8G', '7500', '8GB GDDR6 RAM', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'GPU'));

INSERT INTO PRODUCT
VALUES('MSI GeForce RTX 2080 Ti GAMING X TRIO', '12500', '11GB GDDR6', (SELECT id
		FROM SUPPLIER
		WHERE name = 'MSI'), (SELECT id
		FROM CATEGORY
		WHERE type = 'GPU'));

INSERT INTO PRODUCT
VALUES('EVGA GeForce GTX 1070 Ti FTW2 Gaming', '5000', 'Grafikkort, PCI-Express 3.0, 8GB GDDR5, ICX, Pascal', (SELECT id
		FROM SUPPLIER
		WHERE name = 'EVGA'), (SELECT id
		FROM CATEGORY
		WHERE type = 'GPU'));

INSERT INTO PRODUCT
VALUES('AMD Radeon Pro WX 4100 4GB', '2750', 'Grafikkort, PCI-Express 3.0, GDDR5, 1125/1201MHz, 4x mini-DP, 50W TDP', (SELECT id
		FROM SUPPLIER
		WHERE name = 'AMD'), (SELECT id
		FROM CATEGORY
		WHERE type = 'GPU'));

INSERT INTO PRODUCT
VALUES('Intel Core I7-8700K', '3500', 'Socket-LGA1151, 6-Core, 12-Thread, 3.7/4.7GHz, 95W, Coffee Lake', (SELECT id
		FROM SUPPLIER
		WHERE name = 'INTEL'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPU'));

INSERT INTO PRODUCT
VALUES('Intel Core i9-9900K Processor', '4750', 'Socket-LGA1151, 8-Core, 16-Thread, 3.60/5.0GHz, Coffee Lake Refresh, uden køler', (SELECT id
		FROM SUPPLIER
		WHERE name = 'INTEL'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPU'));

INSERT INTO PRODUCT
VALUES('Intel Core i9-7980XE Processor', '16350', 'Socket-2066, 18-Core, 36-Thread, 2.6/4.4GHz, 165W, 44 PCIe-lanes, uden køler', (SELECT id
		FROM SUPPLIER
		WHERE name = 'INTEL'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPU'));

INSERT INTO PRODUCT
VALUES('AMD Ryzen 7 2700X Processor', '2950', 'Socket-AM4, 8-Core, 16-Thread, 4.35GHz, 20MB cache, 105W, inkl. køler', (SELECT id
		FROM SUPPLIER
		WHERE name = 'AMD'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPU'));

INSERT INTO PRODUCT
VALUES('AMD Ryzen Threadripper 2990WX Processor', '15000', 'Socket-TR4, 32-Core, 64-Thread, 3.0/4.2GHz, 250W, uden køler', (SELECT id
		FROM SUPPLIER
		WHERE name = 'AMD'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPU'));


INSERT INTO PRODUCT
VALUES('HYPER X Predator DDR4 32GB RGB', '3000', '4x8GB 3200MHz RGB', (SELECT id
		FROM SUPPLIER
		WHERE name = 'HYPER X'), (SELECT id
		FROM CATEGORY
		WHERE type = 'RAM'));

INSERT INTO PRODUCT
VALUES('Kingston Value DDR4 2400MHz 16GB ECC', '1900', '2x8GB 2400Mhz DDR4 CL17 1Rx8', (SELECT id
		FROM SUPPLIER
		WHERE name = 'KINGSTON'), (SELECT id
		FROM CATEGORY
		WHERE type = 'RAM'));

INSERT INTO PRODUCT
VALUES('Corsair Vengeance LPX DDR4 3200MHz 32GB', '3500', '2x16GB 3200MHz (PC4-25600) DDR4 CL16, XMP, Sort', (SELECT id
		FROM SUPPLIER
		WHERE name = 'CORSAIR'), (SELECT id
		FROM CATEGORY
		WHERE type = 'RAM'));

INSERT INTO PRODUCT
VALUES('HyperX Fury DDR4 2666MHz 8GB', '900', '2x4GB CL15 Sort', (SELECT id
		FROM SUPPLIER
		WHERE name = 'HYPER X'), (SELECT id
		FROM CATEGORY
		WHERE type = 'RAM'));

INSERT INTO PRODUCT
VALUES('CORSAIR AX 1200i, 1200W PSU', '3000', 'ATX Digital, 80 Plus Platinum, Modular, 6x 6+2-pin PCIe, 16x SATA, 12x Molex', (SELECT id
		FROM SUPPLIER
		WHERE name = 'CORSAIR'), (SELECT id
		FROM CATEGORY
		WHERE type = 'STRØMFORSYNING'));

INSERT INTO PRODUCT
VALUES('ASUS ROG THOR 1200, 1200W PSU', '2700', 'ATX 12V, 80 Plus Platinum, Modular, 6x 6+2 pin PCIe, 3x SATA, 5x Molex', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'STRØMFORSYNING'));


INSERT INTO PRODUCT
VALUES('EVGA GQ 750W Hybrid Modular 80+ PSU', '900', 'ATX 12V , 80 Plus Gold, Modular, 6x 6+2pin PCIe, 9x SATA, 3x Molex, 2x FD', (SELECT id
		FROM SUPPLIER
		WHERE name = 'EVGA'), (SELECT id
		FROM CATEGORY
		WHERE type = 'STRØMFORSYNING'));


INSERT INTO PRODUCT
VALUES('Cooler Master MasterWatt 550', '650', 'ATX 12V, Bronze, 1x 4+4 CPU, 2x 6+2pin PCIe, 6x SATA, 2x Molex, 1x FD', (SELECT id
		FROM SUPPLIER
		WHERE name = 'COOLER MASTER'), (SELECT id
		FROM CATEGORY
		WHERE type = 'STRØMFORSYNING'));


INSERT INTO PRODUCT
VALUES('CORSAIR ML140 PRO LED HVID, 140mm BLÆSER', '250', 'Magnetic Levitation Fan, 140x140x25mm, 400~2000 RPM, 20~97 CFM, 16-37dBA, 4-pin', (SELECT id
		FROM SUPPLIER
		WHERE name = 'CORSAIR'), (SELECT id
		FROM CATEGORY
		WHERE type = 'BLÆSER'));


INSERT INTO PRODUCT
VALUES('NZXT AER 140mm Combo 2x AER & Hue+', '750', '2x AER 140 x 140 x 26 mm, Hue +, RGB', (SELECT id
		FROM SUPPLIER
		WHERE name = 'NZXT'), (SELECT id
		FROM CATEGORY
		WHERE type = 'BLÆSER'));

INSERT INTO PRODUCT
VALUES('Cooler Master MF200R RGB LED Blæser', '235', 'RGB LED, 200x 200 x 25mm, 850 ± 150RPM, 90 CFM, 28 dBA, 3-Pin', (SELECT id
		FROM SUPPLIER
		WHERE name = 'COOLER MASTER'), (SELECT id
		FROM CATEGORY
		WHERE type = 'BLÆSER'));

INSERT INTO PRODUCT
VALUES('Corsair Air AF120 LED Hvid Quiet 120mm', '150', '120 x 120 x 25mm, 1500 RPM, 52.19 CFM, 25.2 dBA, 3-pin, Quiet Edition Blæser', (SELECT id
		FROM SUPPLIER
		WHERE name = 'CORSAIR'), (SELECT id
		FROM CATEGORY
		WHERE type = 'BLÆSER'));

INSERT INTO PRODUCT
VALUES('ASUS ROG STRIX Z390-E GAMINTG', '2100', 'LGA 1151 ATX gaming motherboard with Aura Sync, DDR4 4266 MHz+, dual M.2, SATA 6Gbps, HDMI and USB 3.1 Gen 2', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'BUNDKORT'));

INSERT INTO PRODUCT
VALUES('MSI X470 GAMING PRO CARBON, Socket-AM4', '1800', 'Bundkort, ATX, X470, DDR4, 3xPCIe-x16, SLI/CFX, 2x M.2, USB 3.1, Mystic Light', (SELECT id
		FROM SUPPLIER
		WHERE name = 'MSI'), (SELECT id
		FROM CATEGORY
		WHERE type = 'BUNDKORT'));

INSERT INTO PRODUCT
VALUES('MSI X299 SLI Plus, Socket-2066', '2000', 'Bundkort, ATX, X299, 8xDDR4, 4xPCIe-x16, SLI/CFX, Mystic Light, 2xM.2', (SELECT id
		FROM SUPPLIER
		WHERE name = 'MSI'), (SELECT id
		FROM CATEGORY
		WHERE type = 'BUNDKORT'));

INSERT INTO PRODUCT
VALUES('ASUS Prime B250M-Plus, Socket 1151', '900', 'Bundkort, mATX, B250, DDR4, 2xPCIe-x16, CFX, 2xM.2, USB 3.0', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'BUNDKORT'));


INSERT INTO PRODUCT
VALUES('Corsair Graphite 760T Big Tower Sort', '1500', 'Blæsere: 2x 140mm Front, 1x 140mm Bag, mATX, ATX, USB3.0/2.0, Rød LEDs, Vindue', (SELECT id
		FROM SUPPLIER
		WHERE name = 'CORSAIR'), (SELECT id
		FROM CATEGORY
		WHERE type = 'KABINET'));

INSERT INTO PRODUCT
VALUES('ASUS TUF Gaming GT501 Midi Tower', '1400', 'Blæsere: 3x 120mm front, 1x 140 mm bak, mITX, mATX, ATX, E-ATX, USB 3.1', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'KABINET'));

INSERT INTO PRODUCT
VALUES('NZXT H500 Sort/Blå', '850', 'Blæser: 1x 120 Top, 1x 120mm Bag, ATX, mATX, mITX, Tempered Glass', (SELECT id
		FROM SUPPLIER
		WHERE name = 'NZXT'), (SELECT id
		FROM CATEGORY
		WHERE type = 'KABINET'));

INSERT INTO PRODUCT
VALUES('Cooler Master MasterBox Lite 5 RGB', '700', 'Blæser: Foran 120mm x 3 RGB fläkter, Bag: 120mm x1, ATX, M-ATX, M-ITX', (SELECT id
		FROM SUPPLIER
		WHERE name = 'COOLER MASTER'), (SELECT id
		FROM CATEGORY
		WHERE type = 'KABINET'));

INSERT INTO PRODUCT
VALUES('CRYORIG C7 Cu CPU Cooler', '500', '600~2500RPM, 30 dBA', (SELECT id
		FROM SUPPLIER
		WHERE name = 'CORSAIR'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPULUFTKØLER'));

INSERT INTO PRODUCT
VALUES('Noctua NH-D15 SE-AM4 CPU Køler', '740', 'AMD AM4, 300~1500 RPM, 140,2 m³/h, 19~24 dBA', (SELECT id
		FROM SUPPLIER
		WHERE name = 'NOCTUA'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPULUFTKØLER'));

INSERT INTO PRODUCT
VALUES('Cooler Master MA620P RGB', '750', '2066/2011-v3, AM4/AM3+, 600~1800 RPM, CDC 2.0, ink. RGB LED Controller', (SELECT id
		FROM SUPPLIER
		WHERE name = 'COOLER MASTER'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPULUFTKØLER'));

INSERT INTO PRODUCT
VALUES('Intel TS15A CPU Air Cooler', '375', 'High performance air cooler for Skylake, 130w, works with all LGA115x', (SELECT id
		FROM SUPPLIER
		WHERE name = 'INTEL'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPULUFTKØLER'));

INSERT INTO PRODUCT
VALUES('MSI Core Frozr XL CPU Køler', '900', '2066/2011(-3)/1366/115x, AM4/FM2/AM3', (SELECT id
		FROM SUPPLIER
		WHERE name = 'MSI'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPULUFTKØLER'));


INSERT INTO PRODUCT
VALUES('NZXT Kraken X72 CPU Køler', '1500', '360mm Radiator, 115x support', (SELECT id
		FROM SUPPLIER
		WHERE name = 'NZXT'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPUVANDKØLER'));

INSERT INTO PRODUCT
VALUES('Corsair Hydro H150i PRO RGB CPU Køler', '1600', '360mm radiator, 115x/2011-3/2066, AM2/AM3/AM4, 1600 RPM, 47,3 CFM', (SELECT id
		FROM SUPPLIER
		WHERE name = 'CORSAIR'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPUVANDKØLER'));

INSERT INTO PRODUCT
VALUES('ASUS ROG RYUO 120 CPU Køler', '1350', '120mm Radiator, 115x/2011/2011-3/2066, AM4/TR4', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPUVANDKØLER'));

INSERT INTO PRODUCT
VALUES('EVGA CLC 280 Køler', '1350', '280mm radiator, 115x,2011,2066, AM2/AM3, TR4, 600-2200 RPM, 113,5 CFM', (SELECT id
		FROM SUPPLIER
		WHERE name = 'EVGA'), (SELECT id
		FROM CATEGORY
		WHERE type = 'CPUVANDKØLER'));

INSERT INTO PRODUCT
VALUES('Seagate Barracuda PRO 6TB 3.5'' HDD', '2000', 'SATA 6.0Gb/s, 7200RPM, 256MB cache', (SELECT id
		FROM SUPPLIER
		WHERE name = 'SEAGATE'), (SELECT id
		FROM CATEGORY
		WHERE type = 'HDD'));

INSERT INTO PRODUCT
VALUES('Seagate Barracuda 1TB 2.5" Mobile HDD', '500', 'SATA 6.0Gb/s, 5400RPM, 128MB cache', (SELECT id
		FROM SUPPLIER
		WHERE name = 'SEAGATE'), (SELECT id
		FROM CATEGORY
		WHERE type = 'HDD'));

INSERT INTO PRODUCT
VALUES('Seagate Firecuda 1TB 3.5'' SSHD', '750', 'SATA 6.0Gb/s, 7200RPM, 64MB cache, 8GB Flash enhanced', (SELECT id
		FROM SUPPLIER
		WHERE name = 'SEAGATE'), (SELECT id
		FROM CATEGORY
		WHERE type = 'HDD'));

INSERT INTO PRODUCT
VALUES('Seagate Barracuda 2TB 2.5" Mobile HDD', '800', 'SATA 6.0Gb/s, 5400RPM, 128MB cache', (SELECT id
		FROM SUPPLIER
		WHERE name = 'SEAGATE'), (SELECT id
		FROM CATEGORY
		WHERE type = 'HDD'));

INSERT INTO PRODUCT
VALUES('Samsung 970 PRO 512GB M.2 SSD', '1800', 'M.2 2280, PCIe x4, V-NAND MLC, up to 3500/2300MB/s read/write, 600TBW', (SELECT id
		FROM SUPPLIER
		WHERE name = 'SAMSUNG'), (SELECT id
		FROM CATEGORY
		WHERE type = 'SSD'));

INSERT INTO PRODUCT
VALUES('Kingston A400 240GB 2.5" SSD', '450', 'SATA 3.0, 2.5", TLC, up to 500/350/s read/write, 7mm', (SELECT id
		FROM SUPPLIER
		WHERE name = 'KINGSTON'), (SELECT id
		FROM CATEGORY
		WHERE type = 'SSD'));

INSERT INTO PRODUCT
VALUES('HyperX FURY RGB SSD 480GB', '1450', 'SATA 3.0, 2,5", 3D NAND, up to 550/480MB/s, FURY RGB', (SELECT id
		FROM SUPPLIER
		WHERE name = 'HYPER X'), (SELECT id
		FROM CATEGORY
		WHERE type = 'SSD'));

INSERT INTO PRODUCT
VALUES('Intel 760p 256GB M.2 SSD', '1100', 'M.2 2280, PCIe 3.0 x4, NVMe, 3D2 TLC, up to 3210/1315 MB/s, 144TBW', (SELECT id
		FROM SUPPLIER
		WHERE name = 'INTEL'), (SELECT id
		FROM CATEGORY
		WHERE type = 'SSD'));

INSERT INTO PRODUCT
VALUES('Steelseries Rival 710 Gaming Mus', '800', 'kablet, 7 programmerbare knapper, RGB belysning', (SELECT id
		FROM SUPPLIER
		WHERE name = 'STEELSERIES'), (SELECT id
		FROM CATEGORY
		WHERE type = 'MUS'));

INSERT INTO PRODUCT
VALUES('ASUS ROG Gladius II Origin Gaming Mus', '750', 'kablet, 5 programmerbare knapper, 12000 dpi, rgb belysning, optisk gaming-mus', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'MUS'));

INSERT INTO PRODUCT
VALUES('Razer DeathAdder Elite Chroma Gaming Mus', '750', 'kablet, 7 programmerbare knapper, 16000 dpi, chroma lys, optisk gaming-mus', (SELECT id
		FROM SUPPLIER
		WHERE name = 'RAZER'), (SELECT id
		FROM CATEGORY
		WHERE type = 'MUS'));

INSERT INTO PRODUCT
VALUES('Cooler Master MasterMouse S RGB', '400', 'kablet, 5 programmerbare knapper, 7200 dpi, rgb belysning, optisk gaming-mus', (SELECT id
		FROM SUPPLIER
		WHERE name = 'COOLER MASTER'), (SELECT id
		FROM CATEGORY
		WHERE type = 'MUS'));

INSERT INTO PRODUCT
VALUES('Asus 24" LED VG248QE', '2000', '1920x1080, 144hz, 1ms, 80m:1, Speakers, DVI/HDMI/DP', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'SKÆRME'));

INSERT INTO PRODUCT
VALUES('Asus 24.5" LED ROG Strix FreeSync XG258Q', '3550', '1920x1080, 240hz, 1ms, 1000:1, DP/2xHDMI', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'SKÆRME'));

INSERT INTO PRODUCT
VALUES('MSI Optix 27" LED Curved MAG27CQ', '3550', '2560x1440 VA, 144hz, 1ms, 3000:1, DP/DVI/HDMI', (SELECT id
		FROM SUPPLIER
		WHERE name = 'MSI'), (SELECT id
		FROM CATEGORY
		WHERE type = 'SKÆRME'));

INSERT INTO PRODUCT
VALUES('Samsung 28" 4K LED FreeSync U28E570D', '2600', '3840x2160 UHD-TN, 1ms, 1m:1, HDMI2.0/DP', (SELECT id
		FROM SUPPLIER
		WHERE name = 'SAMSUNG'), (SELECT id
		FROM CATEGORY
		WHERE type = 'SKÆRME'));

INSERT INTO PRODUCT
VALUES('Razer BlackWidow Elite Chroma Gaming Tastatur', '1500', 'kablet, nordisk, razer green switches, rgb belysning, mekanisk spil tastatur', (SELECT id
		FROM SUPPLIER
		WHERE name = 'RAZER'), (SELECT id
		FROM CATEGORY
		WHERE type = 'TASTATUR'));

INSERT INTO PRODUCT
VALUES('Cooler Master MasterKeys L Blå PBT', '780', 'kablet, nordisk, cherry mx blue, pbt taster, mekanisk spil tastatur', (SELECT id
		FROM SUPPLIER
		WHERE name = 'COOLER MASTER'), (SELECT id
		FROM CATEGORY
		WHERE type = 'TASTATUR'));

INSERT INTO PRODUCT
VALUES('Corsair Gaming K95 RGB PLATINUM Speed', '1700', 'kablet, nordisk, cherry mx speed, rgb belysning, mekanisk spil tastatur', (SELECT id
		FROM SUPPLIER
		WHERE name = 'CORSAIR'), (SELECT id
		FROM CATEGORY
		WHERE type = 'TASTATUR'));

INSERT INTO PRODUCT
VALUES('ASUS Cerberus MKII Gaming Tastatur', '620', 'kablet, nordisk, stænktæt, rgb belysing, membran spiltastatur', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'TASTATUR'));

INSERT INTO PRODUCT
VALUES('HyperX Alloy FPS RGB Gaming Tastatur', '950', 'kablet, silver speed switcher, rgb belysning, mekanisk spilltastatur', (SELECT id
		FROM SUPPLIER
		WHERE name = 'HYPER X'), (SELECT id
		FROM CATEGORY
		WHERE type = 'TASTATUR'));

INSERT INTO PRODUCT
VALUES('iiglo Skærmkabel DP - DP 5 m', '300', 'Displayport, DP male - DP male, Retail, Sort, v1.2', (SELECT id
		FROM SUPPLIER
		WHERE name = 'IIGLO'), (SELECT id
		FROM CATEGORY
		WHERE type = 'KABLER'));

INSERT INTO PRODUCT
VALUES('iiglo Netværkskabel RJ45 - RJ45 5 m', '300', 'UTP, RJ45 male - RJ45 male, Hvid, CAT5e', (SELECT id
		FROM SUPPLIER
		WHERE name = 'IIGLO'), (SELECT id
		FROM CATEGORY
		WHERE type = 'KABLER'));

INSERT INTO PRODUCT
VALUES('iiglo Strømkabel C14 - C13 2 m', '150', 'C14 male - C13 female', (SELECT id
		FROM SUPPLIER
		WHERE name = 'IIGLO'), (SELECT id
		FROM CATEGORY
		WHERE type = 'KABLER'));

INSERT INTO PRODUCT
VALUES('iiglo Kabel DP - DVI', '270', 'Kabeladapter, DP male - DVI female, single link', (SELECT id
		FROM SUPPLIER
		WHERE name = 'IIGLO'), (SELECT id
		FROM CATEGORY
		WHERE type = 'KABLER'));

INSERT INTO PRODUCT
VALUES('Intel Pro/1000GT Desktop Adapter', '300', 'PCI, Gigabit', (SELECT id
		FROM SUPPLIER
		WHERE name = 'INTEL'), (SELECT id
		FROM CATEGORY
		WHERE type = 'NETKORT'));

INSERT INTO PRODUCT
VALUES('Asus PCE-AC55BT AC1200 netkort', '450', 'Trådløst netkort med ekstern antenne med Bluetooth 4.0, PCI-E adapter', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'NETKORT'));

INSERT INTO PRODUCT
VALUES('ASUS XG-C100C 10Gb PCIe adapter', '1100', '10Gb Base-T PCIe Network Adapter, backward compatible, RJ45 port, built-in QoS', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'NETKORT'));

INSERT INTO PRODUCT
VALUES('Intel 10Gb Ethernet Network X550-T1', '3000', '10Gb Ethernet 1 port,PCIe 3.0, x4 Low profil', (SELECT id
		FROM SUPPLIER
		WHERE name = 'INTEL'), (SELECT id
		FROM CATEGORY
		WHERE type = 'NETKORT'));

INSERT INTO PRODUCT
VALUES('ASUS Strix Raid DLX Gaming Lydkort', '1400', '7.1, 124dB SNR, audiophile-grade DAC, 600ohm amp, Instant-on Raid Mode', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'LYDKORT'));

INSERT INTO PRODUCT
VALUES('ASUS Xonar AE 7.1 Lydkort', '800', 'PCIe 1x, 3.0, 7.1 kanals surround, hovedtelefonforstærker, ess dac,110dB SRN', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'LYDKORT'));

INSERT INTO PRODUCT
VALUES('HyperX Cloud Eksternt Lydkort', '350', 'usb, 3,5 minijack, led indikator, virtuelle 7.1 surround, til cloud headset', (SELECT id
		FROM SUPPLIER
		WHERE name = 'HYPER X'), (SELECT id
		FROM CATEGORY
		WHERE type = 'LYDKORT'));

INSERT INTO PRODUCT
VALUES('ASUS Xonar DG Lydkort', '350', 'PCI, 5.1 kanals surround, hi fi, hörlursförstärkare, GX 2.5 lyd, 105 dB SRN', (SELECT id
		FROM SUPPLIER
		WHERE name = 'ASUS'), (SELECT id
		FROM CATEGORY
		WHERE type = 'LYDKORT'));

INSERT INTO PRODUCT
VALUES('HyperX Cloud Stinger Gaming Headset', '520', '3.5mm minijack, drejeligt mik, brusreducerande, ørekop kontrol, konsol, pc', (SELECT id
		FROM SUPPLIER
		WHERE name = 'HYPER X'), (SELECT id
		FROM CATEGORY
		WHERE type = 'HEADSET'));

INSERT INTO PRODUCT
VALUES('Razer Kraken TE Gaming Headset Sort Edt', '900', 'usb, optrækkelige mic, støjreduceret, køling gel ørepuder, konsol, pc, thx lyd', (SELECT id
		FROM SUPPLIER
		WHERE name = 'RAZER'), (SELECT id
		FROM CATEGORY
		WHERE type = 'HEADSET'));

INSERT INTO PRODUCT
VALUES('Corsair Void Pro RGB Trådløs Hvid', '1200', 'usb, foldbar mik, genopladelig, støjreduktion, 7.1 surround, gaming headset', (SELECT id
		FROM SUPPLIER
		WHERE name = 'CORSAIR'), (SELECT id
		FROM CATEGORY
		WHERE type = 'HEADSET'));

INSERT INTO PRODUCT
VALUES('Steelseries Arctis Pro Trådløst Headset', '2650', 'optrækkelige mik, genopladelig, støjreduktion, dts, 7.1 surround, gaming headset', (SELECT id
		FROM SUPPLIER
		WHERE name = 'STEELSERIES'), (SELECT id
		FROM CATEGORY
		WHERE type = 'HEADSET'));



ALTER TABLE PRODUCT ADD LastChanged rowversion;

--INSERT INTO UNIQUEPRODUCT
INSERT INTO UNIQUEPRODUCT
VALUES('NO00000011', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '1'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO00000111', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '2'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO00001111', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '3'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11110000', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '4'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11111111', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '5'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11111118', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '6'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11111178', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '7'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11111678', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '8'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11112222', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '9'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11115678', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '10'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11145678', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '11'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11223344', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '12'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11335577', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '13'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO11345678', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '14'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO12345678', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '15'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO22262569', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '16'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO22446688', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '17'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO22863876', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '18'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO22942649', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '19'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO23589986', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '20'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO23623933', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '21'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO24296449', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '22'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO24376759', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '23'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO24866529', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '24'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO24896775', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '25'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO25454532', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '26'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO25698730', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '27'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO25774679', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '28'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO25922788', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '29'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO26325995', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '30'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO26759945', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '31'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO28788957', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '32'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO29223249', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '33'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO29646745', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '34'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO29993452', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '35'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO32103210', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '36'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO33399748', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '37'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO33975373', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '38'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO34653524', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '39'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO34852743', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '40'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO34955983', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '41'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO35287326', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '42'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO35336446', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '43'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO35762384', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '44'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO35939539', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '45'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO36587405', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '46'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO37926943', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '47'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO38354243', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '48'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO39366763', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '49'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO39773525', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '50'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO39828478', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '51'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO42625533', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '52'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO42692448', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '53'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO44564448', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '54'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO46269458', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '55'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO46666225', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '56'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO47287227', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '57'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO47687343', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '58'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO48687247', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '59'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO52563286', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '60'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO53249397', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '61'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO53353427', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '62'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO53865367', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '63'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO54689869', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '64'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO55448899', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '65'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO55667788', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '66'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO56874587', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '67'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO56894478', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '68'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO56976473', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '69'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO58378843', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '70'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO59935969', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '71'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO62898842', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '72'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO63223632', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '73'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO63554993', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '74'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO63594444', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '75'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO64527924', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '1'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO65326545', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '2'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO65406540', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '3'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO66639563', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '4'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO66758958', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '5'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO66785986', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '6'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO66953659', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '7'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO67733672', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '8'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO67857465', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '9'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO68692849', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '10'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO69283424', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '11'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO69332727', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '12'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO73325325', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '13'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO73855983', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '14'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO74107410', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '15'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO74349273', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '16'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO74838597', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '17'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO74938896', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '18'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO75362886', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '19'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO75577432', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '20'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO76238624', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '21'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO76587996', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '22'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO78793885', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '23'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO83449738', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '24'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO83488772', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '25'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO83666335', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '26'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO85208520', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '27'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO85338263', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '28'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO85382882', '30 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '29'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO85636598', '36 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '30'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO86272554', '60 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '31'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO87569840', '180 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '32'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO87833776', '200 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '33'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO89598845', '60 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '34'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO89897484', '365 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '35'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO92536523', '720 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '36'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO92653984', '25 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '37'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO93353576', '35 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '38'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO93397734', '600 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '39'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO95497675', '999 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '40'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO95635326', '1024 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '41'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO96309630', '7 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '42'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO96599297', '200 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '43'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO96799852', '58 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '44'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO96888896', '78 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '45'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO97454859', '78 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '46'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO97636773', '180 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '47'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO97783268', '21 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '48'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO97937978', '180 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '49'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO98326645', '180 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '50'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO98709870', '62 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '51'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO98986422', '35 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '52'));
INSERT INTO UNIQUEPRODUCT
VALUES('NO99872732', '37 Days', (SELECT id
		FROM PRODUCT
		WHERE id = '53'));

ALTER TABLE UNIQUEPRODUCT ADD LastChanged rowversion;

--INSERT INTO ORDERLINE
INSERT INTO ORDERLINE
VALUES
	((SELECT id
		FROM MYORDER
		WHERE id = '1'));

INSERT INTO ORDERLINE
VALUES
	((SELECT id
		FROM MYORDER
		WHERE id = '2'));

INSERT INTO ORDERLINE
VALUES
	((SELECT id
		FROM MYORDER
		WHERE id = '3'));

INSERT INTO ORDERLINE
VALUES
	((SELECT id
		FROM MYORDER
		WHERE id = '4'));


INSERT INTO ORDERLINE
VALUES
	((SELECT id
		FROM MYORDER
		WHERE id = '5'));

INSERT INTO ORDERLINE
VALUES
	((SELECT id
		FROM MYORDER
		WHERE id = '6'));

INSERT INTO ORDERLINE
VALUES
	((SELECT id
		FROM MYORDER
		WHERE id = '7'));

ALTER TABLE ORDERLINE ADD LastChanged rowversion;

--INSERT INTO ORDERLINELIST
INSERT INTO ORDERLINELIST
VALUES((SELECT id
		FROM MYORDER
		WHERE id = '1'), (SELECT id
		FROM PRODUCT
		WHERE id = '1'));

INSERT INTO ORDERLINELIST
VALUES((SELECT id
		FROM MYORDER
		WHERE id = '2'), (SELECT id
		FROM PRODUCT
		WHERE id = '2'));

INSERT INTO ORDERLINELIST
VALUES((SELECT id
		FROM MYORDER
		WHERE id = '3'), (SELECT id
		FROM PRODUCT
		WHERE id = '3'));

INSERT INTO ORDERLINELIST
VALUES((SELECT id
		FROM MYORDER
		WHERE id = '4'), (SELECT id
		FROM PRODUCT
		WHERE id = '4'));

INSERT INTO ORDERLINELIST
VALUES((SELECT id
		FROM MYORDER
		WHERE id = '5'), (SELECT id
		FROM PRODUCT
		WHERE id = '5'));

INSERT INTO ORDERLINELIST
VALUES((SELECT id
		FROM MYORDER
		WHERE id = '6'), (SELECT id
		FROM PRODUCT
		WHERE id = '6'));

INSERT INTO ORDERLINELIST
VALUES((SELECT id
		FROM MYORDER
		WHERE id = '7'), (SELECT id
		FROM PRODUCT
		WHERE id = '7'));

ALTER TABLE ORDERLINELIST ADD LastChanged rowversion;