//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.ProductServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _categoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal _priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _supplierIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _categoryId {
            get {
                return this._categoryIdField;
            }
            set {
                if ((this._categoryIdField.Equals(value) != true)) {
                    this._categoryIdField = value;
                    this.RaisePropertyChanged("_categoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _description {
            get {
                return this._descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this._descriptionField, value) != true)) {
                    this._descriptionField = value;
                    this.RaisePropertyChanged("_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal _price {
            get {
                return this._priceField;
            }
            set {
                if ((this._priceField.Equals(value) != true)) {
                    this._priceField = value;
                    this.RaisePropertyChanged("_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _supplierId {
            get {
                return this._supplierIdField;
            }
            set {
                if ((this._supplierIdField.Equals(value) != true)) {
                    this._supplierIdField = value;
                    this.RaisePropertyChanged("_supplierId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniqueProduct", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class UniqueProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebUI.ProductServiceReference.Product _productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _serialNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _warrantyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebUI.ProductServiceReference.Product _product {
            get {
                return this._productField;
            }
            set {
                if ((object.ReferenceEquals(this._productField, value) != true)) {
                    this._productField = value;
                    this.RaisePropertyChanged("_product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _serialNo {
            get {
                return this._serialNoField;
            }
            set {
                if ((object.ReferenceEquals(this._serialNoField, value) != true)) {
                    this._serialNoField = value;
                    this.RaisePropertyChanged("_serialNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _warranty {
            get {
                return this._warrantyField;
            }
            set {
                if ((object.ReferenceEquals(this._warrantyField, value) != true)) {
                    this._warrantyField = value;
                    this.RaisePropertyChanged("_warranty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Read", ReplyAction="http://tempuri.org/IProductService/ReadResponse")]
        WebUI.ProductServiceReference.Product Read(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Read", ReplyAction="http://tempuri.org/IProductService/ReadResponse")]
        System.Threading.Tasks.Task<WebUI.ProductServiceReference.Product> ReadAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindById", ReplyAction="http://tempuri.org/IProductService/FindByIdResponse")]
        WebUI.ProductServiceReference.Product FindById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindById", ReplyAction="http://tempuri.org/IProductService/FindByIdResponse")]
        System.Threading.Tasks.Task<WebUI.ProductServiceReference.Product> FindByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindUniqueByProduct", ReplyAction="http://tempuri.org/IProductService/FindUniqueByProductResponse")]
        WebUI.ProductServiceReference.UniqueProduct[] FindUniqueByProduct(WebUI.ProductServiceReference.Product product, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindUniqueByProduct", ReplyAction="http://tempuri.org/IProductService/FindUniqueByProductResponse")]
        System.Threading.Tasks.Task<WebUI.ProductServiceReference.UniqueProduct[]> FindUniqueByProductAsync(WebUI.ProductServiceReference.Product product, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAll", ReplyAction="http://tempuri.org/IProductService/GetAllResponse")]
        WebUI.ProductServiceReference.Product[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAll", ReplyAction="http://tempuri.org/IProductService/GetAllResponse")]
        System.Threading.Tasks.Task<WebUI.ProductServiceReference.Product[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : WebUI.ProductServiceReference.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<WebUI.ProductServiceReference.IProductService>, WebUI.ProductServiceReference.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebUI.ProductServiceReference.Product Read(string name) {
            return base.Channel.Read(name);
        }
        
        public System.Threading.Tasks.Task<WebUI.ProductServiceReference.Product> ReadAsync(string name) {
            return base.Channel.ReadAsync(name);
        }
        
        public WebUI.ProductServiceReference.Product FindById(int id) {
            return base.Channel.FindById(id);
        }
        
        public System.Threading.Tasks.Task<WebUI.ProductServiceReference.Product> FindByIdAsync(int id) {
            return base.Channel.FindByIdAsync(id);
        }
        
        public WebUI.ProductServiceReference.UniqueProduct[] FindUniqueByProduct(WebUI.ProductServiceReference.Product product, int amount) {
            return base.Channel.FindUniqueByProduct(product, amount);
        }
        
        public System.Threading.Tasks.Task<WebUI.ProductServiceReference.UniqueProduct[]> FindUniqueByProductAsync(WebUI.ProductServiceReference.Product product, int amount) {
            return base.Channel.FindUniqueByProductAsync(product, amount);
        }
        
        public WebUI.ProductServiceReference.Product[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<WebUI.ProductServiceReference.Product[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
