//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsPCStore.CustomerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _fNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _lNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsPCStore.CustomerServiceReference.ZipCity _zipCityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _address {
            get {
                return this._addressField;
            }
            set {
                if ((object.ReferenceEquals(this._addressField, value) != true)) {
                    this._addressField = value;
                    this.RaisePropertyChanged("_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _email {
            get {
                return this._emailField;
            }
            set {
                if ((object.ReferenceEquals(this._emailField, value) != true)) {
                    this._emailField = value;
                    this.RaisePropertyChanged("_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _fName {
            get {
                return this._fNameField;
            }
            set {
                if ((object.ReferenceEquals(this._fNameField, value) != true)) {
                    this._fNameField = value;
                    this.RaisePropertyChanged("_fName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _lName {
            get {
                return this._lNameField;
            }
            set {
                if ((object.ReferenceEquals(this._lNameField, value) != true)) {
                    this._lNameField = value;
                    this.RaisePropertyChanged("_lName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _phone {
            get {
                return this._phoneField;
            }
            set {
                if ((object.ReferenceEquals(this._phoneField, value) != true)) {
                    this._phoneField = value;
                    this.RaisePropertyChanged("_phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsPCStore.CustomerServiceReference.ZipCity _zipCity {
            get {
                return this._zipCityField;
            }
            set {
                if ((object.ReferenceEquals(this._zipCityField, value) != true)) {
                    this._zipCityField = value;
                    this.RaisePropertyChanged("_zipCity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZipCity", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class ZipCity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _zipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _city {
            get {
                return this._cityField;
            }
            set {
                if ((object.ReferenceEquals(this._cityField, value) != true)) {
                    this._cityField = value;
                    this.RaisePropertyChanged("_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _zipCode {
            get {
                return this._zipCodeField;
            }
            set {
                if ((this._zipCodeField.Equals(value) != true)) {
                    this._zipCodeField = value;
                    this.RaisePropertyChanged("_zipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerNotExistException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions")]
    [System.SerializableAttribute()]
    public partial class CustomerNotExistException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerServiceReference.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/Create", ReplyAction="http://tempuri.org/ICustomerService/CreateResponse")]
        int Create(WindowsFormsPCStore.CustomerServiceReference.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/Create", ReplyAction="http://tempuri.org/ICustomerService/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(WindowsFormsPCStore.CustomerServiceReference.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/Read", ReplyAction="http://tempuri.org/ICustomerService/ReadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsPCStore.CustomerServiceReference.CustomerNotExistException), Action="http://tempuri.org/ICustomerService/ReadCustomerNotExistExceptionFault", Name="CustomerNotExistException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions")]
        WindowsFormsPCStore.CustomerServiceReference.Customer Read(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/Read", ReplyAction="http://tempuri.org/ICustomerService/ReadResponse")]
        System.Threading.Tasks.Task<WindowsFormsPCStore.CustomerServiceReference.Customer> ReadAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/ReadByPhone", ReplyAction="http://tempuri.org/ICustomerService/ReadByPhoneResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsPCStore.CustomerServiceReference.CustomerNotExistException), Action="http://tempuri.org/ICustomerService/ReadByPhoneCustomerNotExistExceptionFault", Name="CustomerNotExistException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions")]
        WindowsFormsPCStore.CustomerServiceReference.Customer ReadByPhone(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/ReadByPhone", ReplyAction="http://tempuri.org/ICustomerService/ReadByPhoneResponse")]
        System.Threading.Tasks.Task<WindowsFormsPCStore.CustomerServiceReference.Customer> ReadByPhoneAsync(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/Update", ReplyAction="http://tempuri.org/ICustomerService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsPCStore.CustomerServiceReference.CustomerNotExistException), Action="http://tempuri.org/ICustomerService/UpdateCustomerNotExistExceptionFault", Name="CustomerNotExistException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions")]
        bool Update(WindowsFormsPCStore.CustomerServiceReference.Customer customer, string oldPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/Update", ReplyAction="http://tempuri.org/ICustomerService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(WindowsFormsPCStore.CustomerServiceReference.Customer customer, string oldPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAll", ReplyAction="http://tempuri.org/ICustomerService/GetAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsPCStore.CustomerServiceReference.CustomerNotExistException), Action="http://tempuri.org/ICustomerService/GetAllCustomerNotExistExceptionFault", Name="CustomerNotExistException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions")]
        WindowsFormsPCStore.CustomerServiceReference.Customer[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAll", ReplyAction="http://tempuri.org/ICustomerService/GetAllResponse")]
        System.Threading.Tasks.Task<WindowsFormsPCStore.CustomerServiceReference.Customer[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : WindowsFormsPCStore.CustomerServiceReference.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<WindowsFormsPCStore.CustomerServiceReference.ICustomerService>, WindowsFormsPCStore.CustomerServiceReference.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Create(WindowsFormsPCStore.CustomerServiceReference.Customer customer) {
            return base.Channel.Create(customer);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(WindowsFormsPCStore.CustomerServiceReference.Customer customer) {
            return base.Channel.CreateAsync(customer);
        }
        
        public WindowsFormsPCStore.CustomerServiceReference.Customer Read(int id) {
            return base.Channel.Read(id);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsPCStore.CustomerServiceReference.Customer> ReadAsync(int id) {
            return base.Channel.ReadAsync(id);
        }
        
        public WindowsFormsPCStore.CustomerServiceReference.Customer ReadByPhone(string phone) {
            return base.Channel.ReadByPhone(phone);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsPCStore.CustomerServiceReference.Customer> ReadByPhoneAsync(string phone) {
            return base.Channel.ReadByPhoneAsync(phone);
        }
        
        public bool Update(WindowsFormsPCStore.CustomerServiceReference.Customer customer, string oldPhone) {
            return base.Channel.Update(customer, oldPhone);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(WindowsFormsPCStore.CustomerServiceReference.Customer customer, string oldPhone) {
            return base.Channel.UpdateAsync(customer, oldPhone);
        }
        
        public WindowsFormsPCStore.CustomerServiceReference.Customer[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsPCStore.CustomerServiceReference.Customer[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
