INSERT INTO ZIPCITY
VALUES
    (7700, 'Thisted');
INSERT INTO ZIPCITY
VALUES
    (7730, 'Hanstholm');
INSERT INTO ZIPCITY
VALUES
    (7741, 'Frøstrup');
INSERT INTO ZIPCITY
VALUES
    (7742, 'Vesløs');
INSERT INTO ZIPCITY
VALUES
    (7752, 'Snedsted');
INSERT INTO ZIPCITY
VALUES
    (7755, 'Bedsted Thy');
INSERT INTO ZIPCITY
VALUES
    (7760, 'Hurup Thy');
INSERT INTO ZIPCITY
VALUES
    (7770, 'Vestervig');
INSERT INTO ZIPCITY
VALUES
    (7900, 'Nykøbing M');
INSERT INTO ZIPCITY
VALUES
    (7950, 'Erslev');
INSERT INTO ZIPCITY
VALUES
    (7960, 'Karby');
INSERT INTO ZIPCITY
VALUES
    (7970, 'Redsted M');
INSERT INTO ZIPCITY
VALUES
    (7980, 'Vils');
INSERT INTO ZIPCITY
VALUES
    (7990, 'Øster Assels');
INSERT INTO ZIPCITY
VALUES
    (9000, 'Aalborg');
INSERT INTO ZIPCITY
VALUES
    (9100, 'Aalborg (postboks)');
INSERT INTO ZIPCITY
VALUES
    (9200, 'Aalborg SV');
INSERT INTO ZIPCITY
VALUES
    (9210, 'Aalborg SØ');
INSERT INTO ZIPCITY
VALUES
    (9220, 'Aalborg Øst');
INSERT INTO ZIPCITY
VALUES
    (9230, 'Svenstrup J');
INSERT INTO ZIPCITY
VALUES
    (9240, 'Nibe');
INSERT INTO ZIPCITY
VALUES
    (9260, 'Gistrup');
INSERT INTO ZIPCITY
VALUES
    (9270, 'Klarup');
INSERT INTO ZIPCITY
VALUES
    (9280, 'Storvorde');
INSERT INTO ZIPCITY
VALUES
    (9293, 'Kongerslev');
INSERT INTO ZIPCITY
VALUES
    (9300, 'Sæby');
INSERT INTO ZIPCITY
VALUES
    (9310, 'Vodskov');
INSERT INTO ZIPCITY
VALUES
    (9320, 'Hjallerup');
INSERT INTO ZIPCITY
VALUES
    (9330, 'Dronninglund');
INSERT INTO ZIPCITY
VALUES
    (9340, 'Asaa');
INSERT INTO ZIPCITY
VALUES
    (9352, 'Dybvad');
INSERT INTO ZIPCITY
VALUES
    (9362, 'Gandrup');
INSERT INTO ZIPCITY
VALUES
    (9370, 'Hals');
INSERT INTO ZIPCITY
VALUES
    (9380, 'Vestbjerg');
INSERT INTO ZIPCITY
VALUES
    (9381, 'Sulsted');
INSERT INTO ZIPCITY
VALUES
    (9382, 'Tylstrup');
INSERT INTO ZIPCITY
VALUES
    (9400, 'Nørresundby');
INSERT INTO ZIPCITY
VALUES
    (9430, 'Vadum');
INSERT INTO ZIPCITY
VALUES
    (9440, 'Aabybro');
INSERT INTO ZIPCITY
VALUES
    (9460, 'Brovst');
INSERT INTO ZIPCITY
VALUES
    (9480, 'Løkken');
INSERT INTO ZIPCITY
VALUES
    (9490, 'Pandrup');
INSERT INTO ZIPCITY
VALUES
    (9492, 'Blokhus');
INSERT INTO ZIPCITY
VALUES
    (9493, 'Saltum');
INSERT INTO ZIPCITY
VALUES
    (9500, 'Hobro');
INSERT INTO ZIPCITY
VALUES
    (9510, 'Arden');
INSERT INTO ZIPCITY
VALUES
    (9520, 'Skørping');
INSERT INTO ZIPCITY
VALUES
    (9530, 'Støvring');
INSERT INTO ZIPCITY
VALUES
    (9541, 'Suldrup');
INSERT INTO ZIPCITY
VALUES
    (9550, 'Mariager');
INSERT INTO ZIPCITY
VALUES
    (9560, 'Hadsund');
INSERT INTO ZIPCITY
VALUES
    (9574, 'Bælum');
INSERT INTO ZIPCITY
VALUES
    (9575, 'Terndrup');
INSERT INTO ZIPCITY
VALUES
    (9600, 'Aars');
INSERT INTO ZIPCITY
VALUES
    (9610, 'Nørager');
INSERT INTO ZIPCITY
VALUES
    (9620, 'Aalestrup');
INSERT INTO ZIPCITY
VALUES
    (9631, 'Gedsted');
INSERT INTO ZIPCITY
VALUES
    (9640, 'Farsø');
INSERT INTO ZIPCITY
VALUES
    (9670, 'Løgstør');
INSERT INTO ZIPCITY
VALUES
    (9681, 'Ranum');
INSERT INTO ZIPCITY
VALUES
    (9690, 'Fjerritslev');
INSERT INTO ZIPCITY
VALUES
    (9700, 'Brønderslev');
INSERT INTO ZIPCITY
VALUES
    (9740, 'Jerslev J');
INSERT INTO ZIPCITY
VALUES
    (9750, 'Østervrå');
INSERT INTO ZIPCITY
VALUES
    (9760, 'Vrå');
INSERT INTO ZIPCITY
VALUES
    (9800, 'Hjørring');
INSERT INTO ZIPCITY
VALUES
    (9830, 'Tårs');
INSERT INTO ZIPCITY
VALUES
    (9850, 'Hirtshals');
INSERT INTO ZIPCITY
VALUES
    (9870, 'Sindal');
INSERT INTO ZIPCITY
VALUES
    (9881, 'Bindslev');
INSERT INTO ZIPCITY
VALUES
    (9900, 'Frederikshavn');
INSERT INTO ZIPCITY
VALUES
    (9940, 'Læsø');
INSERT INTO ZIPCITY
VALUES
    (9970, 'Strandby');
INSERT INTO ZIPCITY
VALUES
    (9981, 'Jerup');
INSERT INTO ZIPCITY
VALUES
    (9982, 'Ålbæk');
INSERT INTO ZIPCITY
VALUES
    (9990, 'Skagen');